In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/pandas/survey_results_public.csv") # Reading .csv files

In [3]:
df.head() # First 5 rows
df.tail() # Last 5 rows

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,...,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,...,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,...,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [4]:
df.shape # this attribute gives tuple of (row,column)

(73268, 79)

In [5]:
df.info() #this method gives detailed info about dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  object
 2   Employment                      71709 non-null  object
 3   RemoteWork                      58958 non-null  object
 4   CodingActivities                58899 non-null  object
 5   EdLevel                         71571 non-null  object
 6   LearnCode                       71580 non-null  object
 7   LearnCodeOnline                 50685 non-null  object
 8   LearnCodeCoursesCert            29389 non-null  object
 9   YearsCode                       71331 non-null  object
 10  YearsCodePro                    51833 non-null  object
 11  DevType                         61302 non-null  object
 12  OrgSize                         51039 non-null  object
 13  PurchaseInfluence               50969 non-null  object
 14  BuyNewTool                      67963 non-null  object
 15  Country                         71771 non-null  object
 16  Currency                        51264 non-null  object
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  object
 19  LanguageHaveWorkedWith          70975 non-null  object
 20  LanguageWantToWorkWith          67027 non-null  object
 21  DatabaseHaveWorkedWith          60121 non-null  object
 22  DatabaseWantToWorkWith          51014 non-null  object
 23  PlatformHaveWorkedWith          49924 non-null  object
 24  PlatformWantToWorkWith          40415 non-null  object
 25  WebframeHaveWorkedWith          53544 non-null  object
 26  WebframeWantToWorkWith          46122 non-null  object
 27  MiscTechHaveWorkedWith          44992 non-null  object
 28  MiscTechWantToWorkWith          36810 non-null  object
 29  ToolsTechHaveWorkedWith         54171 non-null  object
 30  ToolsTechWantToWorkWith         46566 non-null  object
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  object
 32  NEWCollabToolsWantToWorkWith    64108 non-null  object
 33  OpSysProfessional use           65503 non-null  object
 34  OpSysPersonal use               70963 non-null  object
 35  VersionControlSystem            71379 non-null  object
 36  VCInteraction                   68156 non-null  object
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  object
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  object
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  object
 42  OfficeStackSyncWantToWorkWith   47688 non-null  object
 43  Blockchain                      71071 non-null  object
 44  NEWSOSites                      71365 non-null  object
 45  SOVisitFreq                     70961 non-null  object
 46  SOAccount                       71572 non-null  object
 47  SOPartFreq                      58229 non-null  object
 48  SOComm                          71408 non-null  object
 49  Age                             70946 non-null  object
 50  Gender                          70853 non-null  object
 51  Trans                           70315 non-null  object
 52  Sexuality                       66565 non-null  object
 53  Ethnicity                       69474 non-null  object
 54  Accessibility                   67244 non-null  object
 55  MentalHealth                    66447 non-null  object
 56  TBranch                         52670 non-null  object
 57  ICorPM                          36283 non-null  object
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  object
 60  Knowledge_2                     34973 non-null  object
 61  Knowledge_3                     35133 non-null  object
 62  Knowledge_4                     35097 non-null  object
 63  Knowledge_5                     35014 non-null  object
 64  Knowledge_6                     34991 non-null  object
 65  Knowledge_7                     34977 non-null  object
 66  Frequency_1                     35371 non-null  object
 67  Frequency_2                     35344 non-null  object
 68  Frequency_3                     34515 non-null  object
 69  TimeSearching                   36198 non-null  object
 70  TimeAnswering                   36022 non-null  object
 71  Onboarding                      35679 non-null  object
 72  ProfessionalTech                34906 non-null  object
 73  TrueFalse_1                     35819 non-null  object
 74  TrueFalse_2                     35715 non-null  object
 75  TrueFalse_3                     35749 non-null  object
 76  SurveyLength                    70444 non-null  object
 77  SurveyEase                      70508 non-null  object
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), object(73)
memory usage: 44.2+ MB

In [6]:
pd.set_option("display.max_columns",85) # allows you to display max 85 columns
pd.set_option("display.max_rows",78) # allows you to display max 78 row

In [7]:
schema_df = pd.read_csv("/content/drive/MyDrive/pandas/survey_results_schema.csv")

In [8]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...,...
74,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
75,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
76,QID294,TrueFalse_1,Are you involved in supporting new hires durin...,NaN,MC,MAVR
77,QID294,TrueFalse_2,Do you use learning resources provided by your...,NaN,MC,MAVR
78,QID294,TrueFalse_3,Does your employer give you time to learn new ...,NaN,MC,MAVR

In [9]:
schema_df.shape

(79, 6)

In [10]:
df.columns  #it displays all columns as series

Index(['ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith',
       'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity',
       'Accessibility', 'MentalHealth', 'TBranch', 'ICorPM', 'WorkExp',
       'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Onboarding', 'ProfessionalTech', 'TrueFalse_1', 'TrueFalse_2',
       'TrueFalse_3', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [11]:
df["MainBranch"] # Displays a certain column(s)

0                                            None of these
1                           I am a developer by profession
2        I am not primarily a developer, but I write co...
3                           I am a developer by profession
4                           I am a developer by profession
                               ...
73263                       I am a developer by profession
73264                       I am a developer by profession
73265    I am not primarily a developer, but I write co...
73266                       I am a developer by profession
73267    I used to be a developer by profession, but no...
Name: MainBranch, Length: 73268, dtype: object

In [12]:
df["MainBranch"].value_counts() # it classifies responses

I am a developer by profession                                                   53507
I am learning to code                                                             6309
I am not primarily a developer, but I write code sometimes as part of my work     5794
I code primarily as a hobby                                                       4865
None of these                                                                     1497
I used to be a developer by profession, but no longer am                          1296
Name: MainBranch, dtype: int64

In [13]:
df.loc[0,"MainBranch"] # loc and iloc is being used to find certain data(s).Loc,allows user to pass Column name whilst iloc only allows integer.

'None of these'

In [14]:
df.loc[[5,10,15],["MainBranch","YearsCode"]]

                                           MainBranch YearsCode
5   I am not primarily a developer, but I write co...        15
10                     I am a developer by profession         5
15                     I am a developer by profession         4

In [15]:
df.loc[5:15,["MainBranch","YearsCode"]] 
#While using slicing,we don't surround values with brackets

                                           MainBranch YearsCode
5   I am not primarily a developer, but I write co...        15
6                         I code primarily as a hobby         3
7                      I am a developer by profession         1
8                      I am a developer by profession         6
9                      I am a developer by profession        37
10                     I am a developer by profession         5
11  I am not primarily a developer, but I write co...        12
12                     I am a developer by profession        12
13                     I am a developer by profession        22
14                     I am a developer by profession        11
15                     I am a developer by profession         4

In [16]:
df.loc[5:15,"MainBranch":"YearsCode"]

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode
5,"I am not primarily a developer, but I write co...","Student, full-time",NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,15
6,I code primarily as a hobby,"Student, part-time",NaN,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses,NaN,3
7,I am a developer by profession,"Not employed, but looking for work",NaN,NaN,Some college/university study without earning ...,Online Courses or Certification,NaN,Coursera;Udemy,1
8,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Coding Bootcamp,NaN,NaN,6
9,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,37
10,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Written Tutorial...,NaN,5
11,"I am not primarily a developer, but I write co...","Employed, full-time;Independent contractor, fr...",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,NaN,12
12,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,12
13,I am a developer by profession,"Employed, part-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,22
14,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",Fully remote,Hobby;Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Stack Overflow;Video-based O...,NaN,11
15,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media,NaN,NaN,4

In [17]:
schema_df.set_index("qid",inplace=True) # Set index to a certain column values and save the dataframe by inplace=True argument

In [18]:
schema_df.head()

,qname,question,force_resp,type,selector
qid,,,,,
QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR

In [19]:
schema_df.loc["QID16",["question","force_resp"]] #Now we use loc by passing string to index field

question      <div><span style="font-size:19px;"><strong>Hel...
force_resp                                                False
Name: QID16, dtype: object

In [20]:
schema_df.reset_index(inplace=True) #It resets indexes to back what it was
schema_df.head()

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR

In [21]:
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [22]:
df = pd.read_csv("/content/drive/MyDrive/pandas/survey_results_public.csv",index_col="ResponseId") # Specifying a column as index
df.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [23]:
schema_df.set_index("qname",inplace=True)

In [24]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
TrueFalse_1,QID294,Are you involved in supporting new hires durin...,NaN,MC,MAVR
TrueFalse_2,QID294,Do you use learning resources provided by your...,NaN,MC,MAVR
TrueFalse_3,QID294,Does your employer give you time to learn new ...,NaN,MC,MAVR

In [25]:
schema_df.loc["MainBranch","question"] # [index,column] or [[indexes],[columns]]

'Which of the following options best describes you today? Here, by "developer" we mean "someone who writes code." <b>*</b>'

In [26]:
schema_df.sort_index(inplace=True) # it sorts index alphabetically
schema_df.sort_index(ascending=False,inplace=True) # by setting ascendin=False,it will be sorted reverse alphabetically
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
VersionControlSystem,QID283,What are the primary <b>version control system...,False,MC,MAVR
...,...,...,...,...,...
CodingActivities,QID297,Which of the following best describes the code...,False,MC,MAVR
BuyNewTool,QID279,"When buying a new tool or software, how do you...",False,MC,MAVR
Blockchain,QID305,"How favorable are you about blockchain, crypto...",False,MC,SAVR
Age,QID127,What is your age?,False,MC,MAVR
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR

 **FILTERING DATA**

In [27]:
df.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [28]:
filt = (df["Employment"]=="Employed, full-time")
filt

ResponseId
1        False
2         True
3         True
4         True
5         True
         ...
73264     True
73265     True
73266     True
73267     True
73268    False
Name: Employment, Length: 73268, dtype: bool

In [29]:
df[filt].head()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
9,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Coding Bootcamp,NaN,NaN,6,6,"Developer, back-end",I don’t know,I have little or no influence,NaN,Netherlands,EUR European Euro,46000.0,Yearly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emacs;Notepad++,Emacs;Notepad++,Windows,Windows,Git,Command-line;Dedicated version control GUI app...,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Microsoft Teams,Microsoft Teams,Very unfavorable,Stack Overflow for Teams (private knowledge sh...,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not at all",25-34 years old,Woman,No,Prefer to self-describe:,European,"Or, in your own words:","Or, in your own words:",Yes,Independent contributor,6.0,Agree,Disagree,Agree,Agree,Agree,Agree,Disagree,3-5 times a week,3-5 times a week,Never,15-30 minutes a day,Over 120 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,49056.0

In [30]:
df.loc[filt] #It will get you all the data where employment column's value equals to "Employed, full-time"

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
9,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Coding Bootcamp,NaN,NaN,6,6,"Developer, back-end",I don’t know,I have little or no influence,NaN,Netherlands,EUR European Euro,46000.0,Yearly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emacs;Notepad++,Emacs;Notepad++,Windows,Windows,Git,Command-line;Dedicated version control GUI app...,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Microsoft Teams,Microsoft Teams,Very unfavorable,Stack Overflow for Teams (private knowledge sh...,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not at all",25-34 years old,Woman,No,Prefer to self-describe:,European,"Or, in your own words:","Or, in your own words:",Yes,Independent contributor,6.0,Agree,Disagree,Agree,Agree,Agree,Agree,Disagree,3-5 times a week,3-5 times a week,Never,15-30 minutes a day,Over 120 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,49056.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73262,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Programming Game...,Udemy;Codecademy;Pluralsight,9,2,"Developer, full-stack","10,000 or more employees",I have little or no influence,Start a free trial;Visit developer communities...,France,EUR European Euro,36000.0,Yearly,Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL...,Bash/Shell;HTML/CSS;Java;JavaScript;Kotlin;Pyt...,MySQL,Elasticsearch;MongoDB;MySQL;Redis,Microsoft Azure,Microsoft Azure,Angular;Angular.js;Drupal;Node.js,Angular;Node.js,Spring,Spring,Docker;npm,Ansible;Chef;Docker;Kubernetes;npm;Terraform;Yarn,Eclipse;Notepad++;Visual Studio Code,IntelliJ;Visual Studio Code,Linux-based;Windows;Windows Subsystem for Linu...,Windows;Windows Subsystem for Linux (WSL),Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management,NaN,Microsoft Teams,Microsoft Teams,Unfavorable,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",18-24 years old,Man,No,NaN,European,None of the above,None of the above,Yes,Independent contributor,2.0,Agree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,1-2 times a week,3-5 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,"Developer, back-end",100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,Nigeria,USD\tUnited States dollar,60000.0,Yearly,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,Bash/Shell;Go;JavaScript;Python;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud,AWS;DigitalOcean;Google Cloud,Express;FastAPI;Node.js,Express;FastAPI;Node.js,Flutter,NaN,Docker;Homebrew;Kubernetes;npm,Docker;Homebrew;Kubernetes;npm,IPython/Jupyter;Sublime Text;Vim;Visual Studio...,Sublime Text;Vim;Visual Studio Code,macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,Data scientist or machine learning specialist,I don’t know,I have little or no influence,Other (please specify):;Ask developers I know/...,United States of America,USD\tUnited States dollar,107000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;Python,Elasticsearch;MongoDB;Oracle;SQLite,Elasticsearch;Neo4j;SQLite,NaN,NaN,FastAPI;Flask;React.js,FastAPI;React.js,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Tor...,NumPy;Pandas;Torch/PyTorch;Hugging Face Transf...,NaN,NaN,IPython/Jupyter;Notepad++;Spyder;Vim;Visual St...,Notepad++;Spyder;Vim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Rocketchat,NaN,Unsure,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,10+ times a week,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,33,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,NaN,NaN,HTML/CSS;JavaScript;PHP;Python;SQL,C#;HTML/CSS;JavaScript;PHP;Python;SQL,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Managed Hosting;Microsoft Azure;VMware,Firebase;Linode;Managed Hosting;Microsoft Azur...,ASP.NET;React.js,ASP.NET;ASP.NET Core ;Blazor;Laravel;Next.js;R...,.NET;Pandas;React Native,.NET;Cordova;Ionic;Pandas;React Native;Xamarin,npm,npm;Unreal Engine,Spyder;Visual Studio;Visual Studio Code,Spyder;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Lists,Microsoft Lists,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",55-64 years old,Man,No,Straight / Heterosexual,Multiracial,None of the above,None of the above,Yes,Independent contributor,42.0,Disagree,Neither agree nor disagree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,31,"Developer, front-end;Developer, desktop or ent...",10 to 19 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,58500.0,Yearly,C#;Delphi;VBA,Delphi,Microsoft SQL Server;MongoDB;Oracle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"RAD Studio (Delphi, C++ Builder);Visual Studio","RAD Studio (Delphi, C++ Builder);Visual Studio",Windows,Windows,SVN,Dedicated version control GUI application,NaN,NaN,NaN,NaN,Zoom,Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",55-64 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [31]:
df.loc[filt,"MainBranch"]

ResponseId
2                           I am a developer by profession
3        I am not primarily a developer, but I write co...
4                           I am a developer by profession
5                           I am a developer by profession
9                           I am a developer by profession
                               ...
73262                       I am a developer by profession
73264                       I am a developer by profession
73265                       I am a developer by profession
73266    I am not primarily a developer, but I write co...
73267                       I am a developer by profession
Name: MainBranch, Length: 42962, dtype: object

In [32]:
df.loc[filt,["MainBranch","EdLevel"]]  #Using .loc to filter our datas and creating new datasets where our filters applied

,MainBranch,EdLevel
ResponseId,,
2,I am a developer by profession,NaN
3,"I am not primarily a developer, but I write co...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
4,I am a developer by profession,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
5,I am a developer by profession,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
9,I am a developer by profession,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
...,...,...
73262,I am a developer by profession,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
73264,I am a developer by profession,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
73265,I am a developer by profession,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
73266,"I am not primarily a developer, but I write co...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
73267,I am a developer by profession,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"

In [33]:
df2=df.dropna(subset=["YearsCode","YearsCodePro"]) # .dropna method delete rows with na values.In this case,it will only delete rows where indicated subset columns are NaN

In [34]:
filt = ( df["Employment"] == "Employed, full-time") & (df["RemoteWork"]=="Fully remote") #filtering with multiple filters
df.loc[filt]

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
18,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,Coursera;Pluralsight,13,10,"Engineer, data","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,Austria,EUR European Euro,190000.0,Yearly,Python;SQL,Python;SQL,Cassandra;PostgreSQL,Cassandra;PostgreSQL,AWS;Google Cloud,AWS;Google Cloud,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes,Docker;Homebrew;Kubernetes;Terraform,Visual Studio Code,PyCharm;Visual Studio Code,macOS,Windows;Windows Subsystem for Linux (WSL),Git,Command-line,NaN,NaN,NaN,NaN,Slack;Zoom,Slack;Zoom,Indifferent,Stack Overflow for Teams (private knowledge sh...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Woman,No,Straight / Heterosexual,European,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,202623.0
23,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,Something else,Books / Physical media,NaN,NaN,25,20,"Developer, back-end",100 to 499 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Canada,CAD\tCanadian dollar,125000.0,Yearly,C#;SQL;TypeScript,C#;SQL,Microsoft SQL Server;PostgreSQL;Redis,Microsoft SQL Server;PostgreSQL,Google Cloud;Microsoft Azure,NaN,Angular;ASP.NET Core ;React.js,ASP.NET Core,.NET,.NET,Docker;Kubernetes;npm;Terraform;Yarn,Docker,Rider;Visual Studio;Visual Studio Code,Visual Studio,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Confluence,NaN,Google Chat;Microsoft Teams;Slack,Slack,Very unfavorable,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",35-44 years old,Man,No,Straight / Heterosexual,White;North American,None of the above,None of the above,Yes,Independent contributor,23.0,Neither agree nor disagree,Agree,Disagree,Disagree,Disagree,Disagree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,No,No,No,Too long,Neither easy nor difficult,97605.0
32,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;O...,NaN,24,21,"Developer, full-stack","10,000 or more employees",I have some influence,Other (please specify):,United States of America,USD\tUnited States dollar,102000.0,Yearly,C#;HTML/CSS;JavaScript;SQL,TypeScript,Microsoft SQL Server,NaN,Microsoft Azure,NaN,ASP.NET,Angular;ASP.NET Core ;Blazor;Vue.js,.NET,Xamarin,NaN,NaN,Visual Studio,NaN,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, definitely",55-64 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,21.0,Agree,Strongly agree,Strongly disagree,Disagree,Disagree,Strongly agree,Strongly agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Very long,DevOps function,No,Yes,Yes,Appropriate in length,Easy,102000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73228,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Associate degree (A.A., A.S., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Udemy;edX,5,1,"Developer, full-stack",100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,Philippines,PHP\tPhilippine peso,25000.0,Monthly,JavaScript;Python;TypeScript,JavaScript;Kotlin;Python;TypeScript,MongoDB;SQLite,MongoDB;PostgreSQL,NaN,NaN,Angular;Django;Express;Node.js,Angular;Django;Vue.js,NaN,NaN,Docker;npm,Docker;npm,Visual Studio Code,Android Studio;IntelliJ;Visual Studio Code,macOS,Windows;Windows Subsystem for Linux (WSL),Git,Code editor;Command-line;Version control hosti...,NaN,NaN,NaN,NaN,NaN,NaN,Very favorable,Stack Overflow,Multiple times per day,No,NaN,"No, not at all",25-34 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Yes,Independent contributor,1.0,Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Never,Never,Never,Less than 15 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73234,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,NaN,10,3,"Developer, full-stack",20 to 99 employees,I have some influence,Visit developer communities like Stack Overflo...,Russian Federation,RUB\tRussian ruble,80000.0,Monthly,C#;F#;JavaScript,F#;JavaScript;Kotlin,Elasticsearch;Redis,PostgreSQL;Redis,NaN,NaN,Angular.js;ASP.NET Core,ASP.NET Core ;Next.js;React.js;Vue.js,.NET,.NET;Xamarin,Docker;npm;Yarn,Docker,Rider,Android Studio;Rider;Visual Studio Code;Webstorm,Windows;Windows Subsystem for Linux (WSL),Windows,Git,Code editor;Version control hosting service we...,NaN,NaN,NaN,NaN,Microsoft Teams,NaN,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",25-34 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,Independent contributor,3.0,Agree,Disagree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Disagree,Strongly disagree,Never,Never,Never,Over 120 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Continuous integration (CI) an...,No,Yes,No,Appropriate in length,Easy,NaN
73241,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,23,17,"Developer, front-end;Developer, full-stack;Dat...","10,000 or more employees",I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,Bash/Shell;HTML/CSS;JavaScript;PHP;TypeScript,HTML/CSS;JavaScript;PHP,Elasticsearch;MongoDB;MySQL,Firebase Realtime Database,Linode,NaN,Angular;Drupal;Symfony,Vue.js,NaN,NaN,Docker;Homebrew;npm,NaN,Visual Studio Code;Xcode,NaN,Linux-based,macOS,Git,Command-line,NaN,NaN,Confluence;Trello,NaN,Slack;Zoom,NaN,Indifferent,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,I have an anxiety disorder,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73247,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;O...,Coursera;Udemy;Codecademy,10,5,"Developer, back-end;Developer, desktop or ente...","10,000 or more employees",I have some influence,Start a free trial;Ask developers I know/work ...,Russian Federation,RUB\tRussian ruble,150000.0,Monthly,Java;JavaScript;SQL,Java;JavaScript;Kotlin;SQL,Oracle,Oracle,Heroku,AWS,Node.js;React.js,Node.js;React.js,Spring,Spring,Docker;npm;Yarn,Docker;npm;Unity 3D;Unreal Engine;Yarn,Android Studio;IntelliJ;Notepad++;PyCharm,Android Studio;IntelliJ;Notepad++;PyCharm,Windows,Windows,Git,Version control hosting service web GUI,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Cisco Webex Teams;Microsoft Teams;Slack;Zoom,Slack,Favorable,Stack Overflow,A few times per week,No,NaN,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,People manager,5.0,Strongly agree,Neither agree nor disagree,Disagree,Strongly agree,Strongly agree,Strongly agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,"Developer, back-end",100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,Nigeria,USD\tUnited States dollar,60000.0,Yearly,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,Bash/Shell;Go;JavaScript;Python;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud,AWS;DigitalOcean;Google Cloud,Express;FastAPI;Node.js,Express;FastAPI;Node.js,Flutter,NaN,Docker;Homebrew;Kubernetes;npm,Docker;Homebrew;Kubernetes;npm,IPython/Jupyter;Sublime Text;Vim;Visual Studio...,Sublime Text;Vim;Visual Studio Code,macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN

In [35]:
df.loc[filt,"MainBranch":"CodingActivities"] # Displaying certain filtered values using .loc .first argument is to filter rows,second one is to specify columns to display

,MainBranch,Employment,RemoteWork,CodingActivities
ResponseId,,,,
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work
18,I am a developer by profession,"Employed, full-time",Fully remote,Hobby
23,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects
32,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work
...,...,...,...,...
73228,I am a developer by profession,"Employed, full-time",Fully remote,Hobby
73234,I am a developer by profession,"Employed, full-time",Fully remote,Hobby
73241,I am a developer by profession,"Employed, full-time",Fully remote,Hobby
73247,I am a developer by profession,"Employed, full-time",Fully remote,Hobby
73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work

In [36]:
filt = ( df["Employment"] == "Employed, full-time") | (df["RemoteWork"]=="Fully remote")
df.loc[ ~filt, "MainBranch":"CodingActivities"]                                           # ~ indicates the opposite state of given contition
#After filtering data,we use .loc to display it

,MainBranch,Employment,RemoteWork,CodingActivities
ResponseId,,,,
1,None of these,NaN,NaN,NaN
6,"I am not primarily a developer, but I write co...","Student, full-time",NaN,NaN
7,I code primarily as a hobby,"Student, part-time",NaN,NaN
8,I am a developer by profession,"Not employed, but looking for work",NaN,NaN
20,I am learning to code,"Student, full-time",NaN,NaN
...,...,...,...,...
73253,I am learning to code,"Student, part-time",NaN,NaN
73257,I am a developer by profession,"Student, part-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work
73258,I am learning to code,"Student, full-time",NaN,NaN
73261,I am a developer by profession,"Employed, full-time;Student, part-time","Hybrid (some remote, some in-person)",School or academic work
73263,I am learning to code,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work

In [37]:
filt= (df['CompTotal'] > 5000.0) & (df["YearsCode"]=="10")
df[filt]

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
27,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,NaN,10,5,"Developer, full-stack;Developer, back-end",20 to 99 employees,I have little or no influence,Start a free trial,United States of America,USD\tUnited States dollar,106960.0,Yearly,Bash/Shell;Groovy;HTML/CSS;Java;JavaScript;SQL,Bash/Shell;Groovy;HTML/CSS;Java;JavaScript;Python,MongoDB;MySQL,MongoDB,AWS,AWS,jQuery,jQuery;React.js,NaN,NaN,NaN,NaN,Atom;IntelliJ;Vim,Atom;IntelliJ;Vim,macOS,macOS;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,NaN,NaN,Microsoft Teams;Slack;Zoom,Slack,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,White;North American,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,106960.0
74,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Online ...,NaN,10,2,"Developer, full-stack;Developer, QA or test;De...","10,000 or more employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Germany,EUR European Euro,60000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;PowerShell;Pyth...,Bash/Shell;Go;HTML/CSS;JavaScript;Python;Rust;SQL,SQLite,SQLite,AWS;Google Cloud,AWS;Google Cloud,Flask;jQuery;Node.js;Vue.js,Flask;jQuery;Node.js;Vue.js,NaN,NaN,Docker;npm;Terraform;Yarn,Docker;npm;Terraform;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Linux-based;Windows,Windows;Windows Subsystem for Linux (WSL),Git,Command-line,NaN,NaN,Jira Work Management;Stack Overflow for Teams,Jira Work Management;Stack Overflow for Teams,Microsoft Teams;Slack;Zoom,Microsoft Teams;Slack;Zoom,Indifferent,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,Yes,Independent contributor,5.0,Strongly agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,30-60 minutes a day,Very long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,63986.0
86,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,10,7,Data scientist or machine learning specialist;...,100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,United States of America,USD\tUnited States dollar,95000.0,Yearly,Bash/Shell;Java;Python;SQL,Clojure;Dart;Go;Java;JavaScript;Kotlin;Python;...,MariaDB;MySQL,MariaDB;MySQL,NaN,NaN,NaN,NaN,Keras;NumPy;Scikit-learn;TensorFlow;Torch/PyTo...,Flutter;Keras;NumPy;Scikit-learn;Spring;Tensor...,NaN,NaN,Eclipse;Notepad++;PyCharm,Eclipse;IntelliJ;Notepad++;PyCharm,Linux-based;Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,Microsoft Teams;Slack;Zoom,Indifferent,Stack Overflow,Daily or almost daily,No,NaN,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,Prefer not to say,Yes,Independent contributor,7.0,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,6-10 times a week,1-2 times a week,60-120 minutes a day,15-30 minutes a day,Somewhat short,Developer portal or other central places to fi...,No,No,Yes,Appropriate in length,Easy,95000.0
110,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Written Tutorials;Stac...,Udemy;Pluralsight,10,8,"Developer, back-end",20 to 99 employees,I have little or no influence,Start a free trial;Visit developer communities...,Spain,EUR European Euro,42000.0,Yearly,C#;JavaScript;Kotlin;PowerShell;Rust;TypeScript,C#;Go;Rust;TypeScript,Microsoft SQL Server;MySQL;PostgreSQL;Redis;SQ...,Redis;SQLite,AWS;Microsoft Azure,AWS;DigitalOcean;Linode,Angular;ASP.NET;ASP.NET Core ;Node.js;Vue.js,NaN,.NET,.NET,Docker;npm;Terraform,Docker;Kubernetes;Pulumi;Terraform,Android Studio;Rider;Sublime Text;Webstorm,Rider;Sublime Text,Linux-based;Windows;Windows Subsystem for Linu...,Linux-based;Windows;Windows Subsystem for Linu...,Git,Command-line;Version control hosting service w...,NaN,NaN,Confluence;Jira Work Management,NaN,Microsoft Teams;Zoom,Mattermost;Slack,Very unfavorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,Yes,Independent contributor,8.0,Agree,Agree,Strongly agree,Disagree,Disagree,Neither agree nor disagree,Agree,Never,1-2 times a week,1-2 times a week,Over 120 minutes a day,Less than 15 minutes a day,Very long,DevOps function;Developer portal or other cent...,No,No,No,Too long,Neither easy nor difficult,44790.0
159,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Other doctoral degree (Ph.D., Ed.D., etc.)","School (i.e., University, College, etc)",NaN,NaN,10,7,"Engineer, site reliability;DevOps specialist;C...",20 to 99 employees,I have a great deal of influence,Ask developers I know/work with,Germany,EUR European Euro,7200.0,Monthly,Bash/Shell;Groovy;TypeScript,Bash/Shell;Go;Rust;TypeScript,Cassandra;Elasticsearch;MongoDB;Redis,Cassandra;MongoDB;Redis,AWS;Google Cloud;Microsoft Azure,AWS,React.js,React.js,NaN,NaN,Docker;Kubernetes;npm;Terraform;Yarn,Docker;Kubernetes;Terraform;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Linux-based,Linux-based;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Google Chat;Slack;Zoom,Google Chat;Slack,Very unfavorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",25-34 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,Independent contributor,7.0,Strongly agree,Disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Never,10+ times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Somewhat long,Continuous integration (CI) and (more often) c...,Yes,No,Yes,Appropriate in length,Easy,92136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73164,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,10,2,Data scientist or machine learning specialist;...,100 to 499 employees,I have little or no influence,Ask developers I know/work with,United States of America,USD\tUnited States dollar,94000.0,Yearly,Bash/Shell;JavaScript;Python;TypeScript,Bash/Shell;JavaScript;Python;Rust;TypeScript,NaN,NaN,NaN,NaN,Angular;Flask;Node.js,Angular;FastAPI;Flask;Node.js,Torch/PyTorch;Hugging Face Transformers,Torch/PyTorch;Hugging Face Transformers,Ansible;Homebrew;npm,Ansible;Homebrew;npm,Notepad++;PyCharm;Vim;Visual Studio Code,Notepad++;PyCharm;Vim;Visual Studio Code,Linux-based;macOS,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Confluence,NaN,Microsoft Teams;Slack;Zoom,Slack;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",25-34 years old,Woman,Yes,Gay or Lesbian,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,2.0,Strongly agree,Disagree,Strongly agree,Agree,Agree,Agree,Strongly agree,Never,1-2 times a week,Never,15-30 minutes a day,15-30 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73182,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;V...,Coursera;Udemy;Codecademy;Skillsoft,10,6,"Developer, back-end","10,000 or more employees",I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,72000.0,Yearly,Bash/Shell;HTML/CSS;Python;SQL;VBA,Bash/Shell;C#;C++;Go;HTML/CSS;Java;JavaScript;...,IBM DB2;Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL;SQLite,NaN,NaN,Node.js;React.js,Angular.js;Django;FastAPI;Flask;Node.js;React....,NumPy,React Native;Spring,NaN,NaN,Notepad++;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Linux-based;Windows;Other (please specify):,Windows,I don't use one,NaN,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Indifferent,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,35-44 years old,Man,No,Straight / Heterosexual,White;North American,I am deaf / hard of hearing,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,25.0,Strongly agree,Agree,Strongly disagree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,6-10 times a week,15-30 minutes a day,15-30 minutes a day,Very long,Developer portal or other central places to fi...,Yes,Yes,No,Appropriate in length,Neither easy nor difficult,NaN
73231,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Written Tutorial...,Pluralsight,10,7,"Developer, back-end;Cloud infrastructure engineer",20 to 99 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,Australia,AUD\tAustralian dollar,135000.0,Yearly,Bash/Shell;C#;HTML/CSS;JavaScript;Python;SQL,Bash/Shell;HTML/CSS;JavaScript;Python;SQL;Type...,DynamoDB;MySQL;PostgreSQL;Redis;SQLite,DynamoDB;Elasticsearch;PostgreSQL;Redis;SQLite,AWS,AWS;Google Cloud,Django;Flask;Node.js;React.js,Django;Flask;Gatsby;Node.js;React.js,.NET,NumPy;Pandas;React Native,Ansible;Docker;Homebrew;npm;Terraform;Yarn,Ansible;Docker;Homebrew;Kubernetes;npm;Pulumi;...,PyCharm;Sublime Text;Vim;Visual Studio;Webstorm,PyCharm;Sublime Text;Vim;Webstorm,Linux-based;macOS,macOS,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,ClickUp;Confluence;Jira Work Management;Notion...,ClickUp;Confluence;Jira Work Management;monday...,Google Chat;Slack;Zoom,Slack,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White;European,None of the above,I have a concentration and/or memory disorder ...,Yes,Independent contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,1-2 times a week,1-2 times a week,Never,Over 120 minutes a day,60-120 minutes a day,Very short,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73234,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,NaN,10,3,"Developer, full-stack",20 to 99 employees,I have some influence,Visit developer communities like Stack Overflo...,Russian Federation,RUB\tRussian ruble,80000.0,Monthly,C#;F#;JavaScript,F#;JavaScript;Kotlin,Elasticsearch;Redis,PostgreSQL;Redis,NaN,NaN,Angular.js;ASP.NET Core,ASP.NET Core ;Next.js;React.js;Vue.js,.NET,.NET;Xamarin,Docker;npm;Yarn,Docker,Rider,Android Studio;Rider;Visual Studio Code;Webstorm,Windows;Windows Subsystem for Linux (WSL),Windows,Git,Code editor;Version control hosting service we...,NaN,NaN,NaN,NaN,Microsoft Teams,NaN,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",25-34 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,Independent contributor,3.0,Agree,Disagree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Disagree,Strongly disagree,Never,Never,Never,Over 120 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Continuous integration (CI) an...,No,Yes,No,Appropriate in length,Easy,NaN
73247,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;O...,Coursera;Udemy;Codecademy,10,5,"Developer, back-end;Developer, desktop or ente...","10,000 or more employees",I have some influence,Start a free trial;Ask developers I know/work ...,Russian Federation,RUB\tRussian ruble,150000.0,Monthly,Java;JavaScript;SQL,Java;JavaScript;Kotlin;SQL,Oracle,Oracle,Heroku,AWS,Node.js;React.js,Node.js;React.js,Spring,Spring,Docker;npm;Yarn,Docker;npm;Unity 3D;Unreal Engine;Yarn,Android Studio;IntelliJ;Notepad++;PyCharm,Android Studio;IntelliJ;Notepad++;PyCharm,Windows,Windows,Git,Version control hosting service web GUI,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Cisco Webex Teams;Microsoft Teams;Slack;Zoom,Slack,Favorable,Stack Overflow,A few times per week,No,NaN,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,People manager,5.0,Strongly agree,Neither agree nor disagree,Disagree,Strongly agree,Strongly agree,Strongly agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN

In [38]:
df.loc[filt,["MainBranch",	"Employment",	"RemoteWork"]]

,MainBranch,Employment,RemoteWork
ResponseId,,,
27,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
74,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
86,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
110,I am a developer by profession,"Employed, full-time",Fully remote
159,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
...,...,...,...
73164,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
73182,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)"
73231,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)"
73234,I am a developer by profession,"Employed, full-time",Fully remote
73247,I am a developer by profession,"Employed, full-time",Fully remote

In [39]:
countries=["United States","India","United Kingdom","Germany","Canada","Turkey"]

filt = df["Country"].isin(countries)  # .isin() method allows to check if the value contains any elementsS of given list
df.loc[filt,["Country","Currency"]]

            Country              Currency
ResponseId
2            Canada  CAD\tCanadian dollar
6           Germany                   NaN
7             India                   NaN
8             India                   NaN
23           Canada  CAD\tCanadian dollar
...             ...                   ...
73256         India     INR\tIndian rupee
73258         India                   NaN
73259         India     INR\tIndian rupee
73263       Germany                   NaN
73268        Canada                   NaN

[15544 rows x 2 columns]

In [40]:
filt =df["LanguageHaveWorkedWith"].str.contains("Python",na=False) # We are checking if that value contains String of "Python"
df.loc[filt, "LanguageHaveWorkedWith"]

ResponseId
3                        C#;C++;HTML/CSS;JavaScript;Python
7            C++;HTML/CSS;JavaScript;PHP;Python;TypeScript
12       C#;HTML/CSS;JavaScript;PowerShell;Python;Rust;SQL
15             HTML/CSS;JavaScript;PHP;Python;R;Ruby;Scala
17                                    C#;Java;PHP;Python;R
                               ...
73258                                         C;Python;SQL
73262    Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL...
73264    Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...
73265            Bash/Shell;HTML/CSS;JavaScript;Python;SQL
73266                   HTML/CSS;JavaScript;PHP;Python;SQL
Name: LanguageHaveWorkedWith, Length: 34155, dtype: object

**Uptading Rows and Columns**

In [41]:
df.columns=[x.upper() for x in df.columns]

In [42]:
df.columns

Index(['MAINBRANCH', 'EMPLOYMENT', 'REMOTEWORK', 'CODINGACTIVITIES', 'EDLEVEL',
       'LEARNCODE', 'LEARNCODEONLINE', 'LEARNCODECOURSESCERT', 'YEARSCODE',
       'YEARSCODEPRO', 'DEVTYPE', 'ORGSIZE', 'PURCHASEINFLUENCE', 'BUYNEWTOOL',
       'COUNTRY', 'CURRENCY', 'COMPTOTAL', 'COMPFREQ',
       'LANGUAGEHAVEWORKEDWITH', 'LANGUAGEWANTTOWORKWITH',
       'DATABASEHAVEWORKEDWITH', 'DATABASEWANTTOWORKWITH',
       'PLATFORMHAVEWORKEDWITH', 'PLATFORMWANTTOWORKWITH',
       'WEBFRAMEHAVEWORKEDWITH', 'WEBFRAMEWANTTOWORKWITH',
       'MISCTECHHAVEWORKEDWITH', 'MISCTECHWANTTOWORKWITH',
       'TOOLSTECHHAVEWORKEDWITH', 'TOOLSTECHWANTTOWORKWITH',
       'NEWCOLLABTOOLSHAVEWORKEDWITH', 'NEWCOLLABTOOLSWANTTOWORKWITH',
       'OPSYSPROFESSIONAL USE', 'OPSYSPERSONAL USE', 'VERSIONCONTROLSYSTEM',
       'VCINTERACTION', 'VCHOSTINGPERSONAL USE', 'VCHOSTINGPROFESSIONAL USE',
       'OFFICESTACKASYNCHAVEWORKEDWITH', 'OFFICESTACKASYNCWANTTOWORKWITH',
       'OFFICESTACKSYNCHAVEWORKEDWITH', 'OFFICESTACKSYNCWANTTOWORKWITH',
       'BLOCKCHAIN', 'NEWSOSITES', 'SOVISITFREQ', 'SOACCOUNT', 'SOPARTFREQ',
       'SOCOMM', 'AGE', 'GENDER', 'TRANS', 'SEXUALITY', 'ETHNICITY',
       'ACCESSIBILITY', 'MENTALHEALTH', 'TBRANCH', 'ICORPM', 'WORKEXP',
       'KNOWLEDGE_1', 'KNOWLEDGE_2', 'KNOWLEDGE_3', 'KNOWLEDGE_4',
       'KNOWLEDGE_5', 'KNOWLEDGE_6', 'KNOWLEDGE_7', 'FREQUENCY_1',
       'FREQUENCY_2', 'FREQUENCY_3', 'TIMESEARCHING', 'TIMEANSWERING',
       'ONBOARDING', 'PROFESSIONALTECH', 'TRUEFALSE_1', 'TRUEFALSE_2',
       'TRUEFALSE_3', 'SURVEYLENGTH', 'SURVEYEASE', 'CONVERTEDCOMPYEARLY'],
      dtype='object')

In [43]:
columns = df.columns.str.replace("_"," ",) #Using str methods,we can manipulate datas.
columns

Index(['MAINBRANCH', 'EMPLOYMENT', 'REMOTEWORK', 'CODINGACTIVITIES', 'EDLEVEL',
       'LEARNCODE', 'LEARNCODEONLINE', 'LEARNCODECOURSESCERT', 'YEARSCODE',
       'YEARSCODEPRO', 'DEVTYPE', 'ORGSIZE', 'PURCHASEINFLUENCE', 'BUYNEWTOOL',
       'COUNTRY', 'CURRENCY', 'COMPTOTAL', 'COMPFREQ',
       'LANGUAGEHAVEWORKEDWITH', 'LANGUAGEWANTTOWORKWITH',
       'DATABASEHAVEWORKEDWITH', 'DATABASEWANTTOWORKWITH',
       'PLATFORMHAVEWORKEDWITH', 'PLATFORMWANTTOWORKWITH',
       'WEBFRAMEHAVEWORKEDWITH', 'WEBFRAMEWANTTOWORKWITH',
       'MISCTECHHAVEWORKEDWITH', 'MISCTECHWANTTOWORKWITH',
       'TOOLSTECHHAVEWORKEDWITH', 'TOOLSTECHWANTTOWORKWITH',
       'NEWCOLLABTOOLSHAVEWORKEDWITH', 'NEWCOLLABTOOLSWANTTOWORKWITH',
       'OPSYSPROFESSIONAL USE', 'OPSYSPERSONAL USE', 'VERSIONCONTROLSYSTEM',
       'VCINTERACTION', 'VCHOSTINGPERSONAL USE', 'VCHOSTINGPROFESSIONAL USE',
       'OFFICESTACKASYNCHAVEWORKEDWITH', 'OFFICESTACKASYNCWANTTOWORKWITH',
       'OFFICESTACKSYNCHAVEWORKEDWITH', 'OFFICESTACKSYNCWANTTOWORKWITH',
       'BLOCKCHAIN', 'NEWSOSITES', 'SOVISITFREQ', 'SOACCOUNT', 'SOPARTFREQ',
       'SOCOMM', 'AGE', 'GENDER', 'TRANS', 'SEXUALITY', 'ETHNICITY',
       'ACCESSIBILITY', 'MENTALHEALTH', 'TBRANCH', 'ICORPM', 'WORKEXP',
       'KNOWLEDGE 1', 'KNOWLEDGE 2', 'KNOWLEDGE 3', 'KNOWLEDGE 4',
       'KNOWLEDGE 5', 'KNOWLEDGE 6', 'KNOWLEDGE 7', 'FREQUENCY 1',
       'FREQUENCY 2', 'FREQUENCY 3', 'TIMESEARCHING', 'TIMEANSWERING',
       'ONBOARDING', 'PROFESSIONALTECH', 'TRUEFALSE 1', 'TRUEFALSE 2',
       'TRUEFALSE 3', 'SURVEYLENGTH', 'SURVEYEASE', 'CONVERTEDCOMPYEARLY'],
      dtype='object')

In [44]:
df.rename(columns={'MAINBRANCH':"MainBranch", 'EMPLOYMENT':"Employment", 'REMOTEWORK':"RemoteWork", 'CODINGACTIVITIES':"CodingActivities"},inplace=True)

In [45]:
df.loc[2,"RemoteWork"] = "FullyRemote"  #we can change specific values 
df.loc[2,"RemoteWork"]

'FullyRemote'

In [46]:
df.loc[2,["RemoteWork","Employment"]] = ["FullyRemote","Retired"]

In [47]:
df.loc[2,["RemoteWork","Employment"]]

RemoteWork    FullyRemote
Employment        Retired
Name: 2, dtype: object

**Changing Multiple Data**

In [48]:
df["RemoteWork"]=df["RemoteWork"].str.lower()
df["RemoteWork"]

ResponseId
1                                         NaN
2                                 fullyremote
3        hybrid (some remote, some in-person)
4                                fully remote
5        hybrid (some remote, some in-person)
                         ...
73264                            fully remote
73265                          full in-person
73266    hybrid (some remote, some in-person)
73267    hybrid (some remote, some in-person)
73268                            fully remote
Name: RemoteWork, Length: 73268, dtype: object

**Multiple Data Change Methods**:


*   apply
*   map
*   replace
*   applymap

In [49]:
#APPLY

# Using "apply" to a series,does the given function to the series
df["MainBranch"].apply(len)

ResponseId
1        13
2        30
3        77
4        30
5        30
         ..
73264    30
73265    30
73266    77
73267    30
73268    56
Name: MainBranch, Length: 73268, dtype: int64

In [50]:
def updateLetter(given_value):
  return given_value.upper()

In [51]:
df["COUNTRY"].fillna("this was na").apply(updateLetter)

ResponseId
1                                              THIS WAS NA
2                                                   CANADA
3        UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...
4                                                   ISRAEL
5                                 UNITED STATES OF AMERICA
                               ...
73264                                              NIGERIA
73265                             UNITED STATES OF AMERICA
73266                             UNITED STATES OF AMERICA
73267    UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...
73268                                               CANADA
Name: COUNTRY, Length: 73268, dtype: object

In [52]:
#Instead of using regular functions,we can use Lmbda Functions
df["COUNTRY"].fillna("This was na").apply(lambda x: x.lower())

ResponseId
1                                              this was na
2                                                   canada
3        united kingdom of great britain and northern i...
4                                                   israel
5                                 united states of america
                               ...
73264                                              nigeria
73265                             united states of america
73266                             united states of america
73267    united kingdom of great britain and northern i...
73268                                               canada
Name: COUNTRY, Length: 73268, dtype: object

In [53]:
df.apply(len) # if we use apply for our database,it will be applied for columns.
df.apply(len,axis="columns") #If we pass "columns" value to the "axis" argumet,function we passed to the apply method will be executed for rows

ResponseId
1        78
2        78
3        78
4        78
5        78
         ..
73264    78
73265    78
73266    78
73267    78
73268    78
Length: 73268, dtype: int64

In [54]:
df["COUNTRY"].fillna("No Country",inplace=True)
df["COUNTRY"].apply(len) #We can use it for particular columns(Series)

ResponseId
1        10
2         6
3        52
4         6
5        24
         ..
73264     7
73265    24
73266    24
73267    52
73268     6
Name: COUNTRY, Length: 73268, dtype: int64

In [55]:
df.loc[0:10,["COUNTRY","MainBranch"]].apply(pd.Series.min) # It Sorts given Columns

COUNTRY                               Canada
MainBranch    I am a developer by profession
dtype: object

In [56]:
df.loc[0:10,["COUNTRY","MainBranch"]].apply(lambda x:x.min()) # Lambda version of the sorting function above

COUNTRY                               Canada
MainBranch    I am a developer by profession
dtype: object

In [57]:
df2=df.loc[0:10,["COUNTRY","MainBranch"]]

In [58]:
df2.applymap(len) #applymap applies function to every element of dataframe

            COUNTRY  MainBranch
ResponseId
1                10          13
2                 6          30
3                52          77
4                 6          30
5                24          30
6                 7          77
7                 5          27
8                 5          30
9                11          30
10                7          30

In [59]:
df.fillna("Empty String",inplace=True)

In [60]:
df2=df2.applymap(str.lower)
df2

,COUNTRY,MainBranch
ResponseId,,
1,no country,none of these
2,canada,i am a developer by profession
3,united kingdom of great britain and northern i...,"i am not primarily a developer, but i write co..."
4,israel,i am a developer by profession
5,united states of america,i am a developer by profession
6,germany,"i am not primarily a developer, but i write co..."
7,india,i code primarily as a hobby
8,india,i am a developer by profession
9,netherlands,i am a developer by profession
10,croatia,i am a developer by profession

In [61]:
df2["COUNTRY"].map({"no country":"not given"}) # it replaced intended values but also replaced NaN with values that are not indicated.So we use "replace" method to change values

ResponseId
1     not given
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
Name: COUNTRY, dtype: object

In [62]:
df2["COUNTRY"].replace({"no country":"not given"})  # Now it changed given values whilst the ones that are not indicated stay the same before

ResponseId
1                                             not given
2                                                canada
3     united kingdom of great britain and northern i...
4                                                israel
5                              united states of america
6                                               germany
7                                                 india
8                                                 india
9                                           netherlands
10                                              croatia
Name: COUNTRY, dtype: object

In [63]:
df2.rename(columns={"COUNTRY":"Countries"},inplace = True)

In [64]:
df2["Countries"]

ResponseId
1                                            no country
2                                                canada
3     united kingdom of great britain and northern i...
4                                                israel
5                              united states of america
6                                               germany
7                                                 india
8                                                 india
9                                           netherlands
10                                              croatia
Name: Countries, dtype: object

ADDING/REMOVİNG ROWS AND COLUMNS

In [65]:
people = {
    'first': ['Corey', 'Jane', 'John'], 
    'last': ['Schafer', 'Doe', 'Doe'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

names = pd.DataFrame(people)
names

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [66]:
names["full_name"] = names["first"] + " " +  names["last"]   #Adding column
names

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [67]:
names.drop(columns=["first","last"],inplace=True)   #Removing columns
names

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [68]:
names["full_name"].str.split(" ")

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [69]:
names["full_name"].str.split(" ",expand=True) #Using expand will designate all lists into a dataframe

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [70]:
names[["first","last"]] = names["full_name"].str.split(" ",expand=True) #We use brackets inside brackets to add multiple column 
names

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [71]:
 names.append({"first":"Yusuf"},ignore_index=True) #Adding rows to a dataframe

<ipython-input-71-6bbf3923044e>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append({"first":"Yusuf"},ignore_index=True) #Adding rows to a dataframe

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN  Yusuf      NaN

In [72]:
people={
    "first":["Tony","Steve"],
    "last": ["Stark","Rogers"],
    "email":["TonyStark@avenge.com","Cap@avenge.com"]
}
df2 = pd.DataFrame(people)
df2

   first    last                 email
0   Tony   Stark  TonyStark@avenge.com
1  Steve  Rogers        Cap@avenge.com

In [73]:
names.append(df2,ignore_index=True) #How to append a dataframe  to another one

<ipython-input-73-cd3c7a9e76d6>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append(df2,ignore_index=True) #How to append a dataframe  to another one

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3     TonyStark@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [74]:
names=names.append(df2,ignore_index=True,sort=False) #sort= False argument helps us to manage sorting datas but since append is deprecated,it's wise to use pd.concat instead.
names

<ipython-input-74-ac8567d7de7a>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names=names.append(df2,ignore_index=True,sort=False) #sort= False argument helps us to manage sorting datas but since append is deprecated,it's wise to use pd.concat instead.

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3     TonyStark@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [75]:
names.drop(index=4,inplace=False) #Deleting the indexes

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3     TonyStark@avenge.com            NaN   Tony    Stark

In [76]:
filt=(names["last"]=="Doe")
names.drop(index = names[filt].index,inplace=True) #Removing certain rows with filtering
names

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3     TonyStark@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

**SORTING DATA**

In [77]:
names.sort_values(by="last",ascending=False) #Sorting by the column 'last' which consisted from string values.So it sorts alphabetically,it was consisted from numbers,it would've been sorted numerically

                     email      full_name  first     last
3     TonyStark@avenge.com            NaN   Tony    Stark
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4           Cap@avenge.com            NaN  Steve   Rogers

In [78]:
names.sort_values(by=["last","first"],ascending=True)  #if they have identical "last" value, it will sort by the second sorting parameter which is "first"

                     email      full_name  first     last
4           Cap@avenge.com            NaN  Steve   Rogers
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3     TonyStark@avenge.com            NaN   Tony    Stark

In [79]:
names.sort_values(by=["last","first"],ascending=[False,True]) # in last ascending order is false,in first ascending order is true

                     email      full_name  first     last
3     TonyStark@avenge.com            NaN   Tony    Stark
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4           Cap@avenge.com            NaN  Steve   Rogers

In [80]:
names.sort_index() #sorting index

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3     TonyStark@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [81]:
names["last"].sort_values() #sorting a single column

4     Rogers
0    Schafer
3      Stark
Name: last, dtype: object

In [82]:
df.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EDLEVEL,LEARNCODE,LEARNCODEONLINE,LEARNCODECOURSESCERT,YEARSCODE,YEARSCODEPRO,DEVTYPE,ORGSIZE,PURCHASEINFLUENCE,BUYNEWTOOL,COUNTRY,CURRENCY,COMPTOTAL,COMPFREQ,LANGUAGEHAVEWORKEDWITH,LANGUAGEWANTTOWORKWITH,DATABASEHAVEWORKEDWITH,DATABASEWANTTOWORKWITH,PLATFORMHAVEWORKEDWITH,PLATFORMWANTTOWORKWITH,WEBFRAMEHAVEWORKEDWITH,WEBFRAMEWANTTOWORKWITH,MISCTECHHAVEWORKEDWITH,MISCTECHWANTTOWORKWITH,TOOLSTECHHAVEWORKEDWITH,TOOLSTECHWANTTOWORKWITH,NEWCOLLABTOOLSHAVEWORKEDWITH,NEWCOLLABTOOLSWANTTOWORKWITH,OPSYSPROFESSIONAL USE,OPSYSPERSONAL USE,VERSIONCONTROLSYSTEM,VCINTERACTION,VCHOSTINGPERSONAL USE,VCHOSTINGPROFESSIONAL USE,OFFICESTACKASYNCHAVEWORKEDWITH,OFFICESTACKASYNCWANTTOWORKWITH,OFFICESTACKSYNCHAVEWORKEDWITH,OFFICESTACKSYNCWANTTOWORKWITH,BLOCKCHAIN,NEWSOSITES,SOVISITFREQ,SOACCOUNT,SOPARTFREQ,SOCOMM,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,ACCESSIBILITY,MENTALHEALTH,TBRANCH,ICORPM,WORKEXP,KNOWLEDGE_1,KNOWLEDGE_2,KNOWLEDGE_3,KNOWLEDGE_4,KNOWLEDGE_5,KNOWLEDGE_6,KNOWLEDGE_7,FREQUENCY_1,FREQUENCY_2,FREQUENCY_3,TIMESEARCHING,TIMEANSWERING,ONBOARDING,PROFESSIONALTECH,TRUEFALSE_1,TRUEFALSE_2,TRUEFALSE_3,SURVEYLENGTH,SURVEYEASE,CONVERTEDCOMPYEARLY
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None of these,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,No Country,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String
2,I am a developer by profession,Retired,fullyremote,Hobby;Contribute to open-source projects,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Canada,CAD\tCanadian dollar,Empty String,Empty String,JavaScript;TypeScript,Rust;TypeScript,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,macOS,Windows Subsystem for Linux (WSL),Git,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Difficult,Empty String
3,"I am not primarily a developer, but I write co...","Employed, full-time","hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Empty String,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,Empty String,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,Empty String,Empty String,Angular.js,Angular;Angular.js,Pandas,.NET,Empty String,Empty String,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,Empty String,Empty String,Empty String,Empty String,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",Empty String,Empty String,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,Empty String,Empty String,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,Empty String,Empty String,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,Empty String,Empty String,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,Empty String,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,Empty String,Empty String,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,Empty String,Empty String,Empty String,Empty String,Microsoft Teams;Zoom,Empty String,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Easy,Empty String

In [83]:
df.sort_values(by="COUNTRY",inplace=True)

In [84]:
df["COUNTRY"]

ResponseId
69587    Afghanistan
56189    Afghanistan
71716    Afghanistan
33329    Afghanistan
67667    Afghanistan
            ...
4719        Zimbabwe
57743       Zimbabwe
25819       Zimbabwe
71358       Zimbabwe
30391       Zimbabwe
Name: COUNTRY, Length: 73268, dtype: object

In [85]:
df[["COUNTRY","CONVERTEDCOMPYEARLY"]].head(50)

                COUNTRY CONVERTEDCOMPYEARLY
ResponseId
69587       Afghanistan        Empty String
56189       Afghanistan        Empty String
71716       Afghanistan        Empty String
33329       Afghanistan        Empty String
67667       Afghanistan        Empty String
28435       Afghanistan        Empty String
21766       Afghanistan        Empty String
33429       Afghanistan        Empty String
61936       Afghanistan        Empty String
60517       Afghanistan        Empty String
3776        Afghanistan        Empty String
42123       Afghanistan        Empty String
43691       Afghanistan             13212.0
6243        Afghanistan              5280.0
30851       Afghanistan        Empty String
53961       Afghanistan        Empty String
56267       Afghanistan        Empty String
23162       Afghanistan        Empty String
10911       Afghanistan        Empty String
2449        Afghanistan             10894.0
49274       Afghanistan              1634.0
23224       Afghanistan              5280.0
5465        Afghanistan        Empty String
55310       Afghanistan        Empty String
22877       Afghanistan        Empty String
55666       Afghanistan              2400.0
7945        Afghanistan        Empty String
34044       Afghanistan        Empty String
25963       Afghanistan        Empty String
67566       Afghanistan        Empty String
60626       Afghanistan        Empty String
24813       Afghanistan        Empty String
70466       Afghanistan        Empty String
29705       Afghanistan        Empty String
28583       Afghanistan        Empty String
4503        Afghanistan        Empty String
8891        Afghanistan        Empty String
46423       Afghanistan        Empty String
26618       Afghanistan        Empty String
60147       Afghanistan        Empty String
3887        Afghanistan        Empty String
61768       Afghanistan        Empty String
32133       Afghanistan        Empty String
15608       Afghanistan        Empty String
19202       Afghanistan        Empty String
6777        Afghanistan        Empty String
10234       Afghanistan        Empty String
30041       Afghanistan        Empty String
17039       Afghanistan        Empty String
2738        Afghanistan        Empty String

In [86]:
df.sort_values(by=["COUNTRY","CONVERTEDCOMPYEARLY"],ascending=[False,True],inplace=True)

In [87]:
df[["CONVERTEDCOMPYEARLY","COUNTRY"]].head(10)

           CONVERTEDCOMPYEARLY   COUNTRY
ResponseId
44536                   3600.0  Zimbabwe
31003                   7200.0  Zimbabwe
66478                  10000.0  Zimbabwe
71980                  10800.0  Zimbabwe
30291                  12000.0  Zimbabwe
64032                  13200.0  Zimbabwe
59418                  75000.0  Zimbabwe
36078                 568968.0  Zimbabwe
46673             Empty String  Zimbabwe
52824             Empty String  Zimbabwe

In [88]:
df["CONVERTEDCOMPYEARLY"].replace("Empty String",0,inplace=True)
df["CONVERTEDCOMPYEARLY"] = df["CONVERTEDCOMPYEARLY"].astype(float) #Chnaging the type of dataframe or column

In [89]:
df["CONVERTEDCOMPYEARLY"].nlargest(10) #Fetches the largest 10 value

ResponseId
40305    50000000.0
202      44790396.0
62027    35000000.0
70523    32500000.0
61044    28853768.0
18923    22500000.0
62224    22500000.0
66496    18000000.0
1291     15000000.0
24164    15000000.0
Name: CONVERTEDCOMPYEARLY, dtype: float64

In [90]:
df["CONVERTEDCOMPYEARLY"].nsmallest(10) #Fetches the smallest 10 value

ResponseId
46673    0.0
52824    0.0
19594    0.0
24120    0.0
68960    0.0
38746    0.0
43528    0.0
72145    0.0
44771    0.0
25845    0.0
Name: CONVERTEDCOMPYEARLY, dtype: float64

GROUPING & AGGREGATING

In [91]:
df.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EDLEVEL,LEARNCODE,LEARNCODEONLINE,LEARNCODECOURSESCERT,YEARSCODE,YEARSCODEPRO,DEVTYPE,ORGSIZE,PURCHASEINFLUENCE,BUYNEWTOOL,COUNTRY,CURRENCY,COMPTOTAL,COMPFREQ,LANGUAGEHAVEWORKEDWITH,LANGUAGEWANTTOWORKWITH,DATABASEHAVEWORKEDWITH,DATABASEWANTTOWORKWITH,PLATFORMHAVEWORKEDWITH,PLATFORMWANTTOWORKWITH,WEBFRAMEHAVEWORKEDWITH,WEBFRAMEWANTTOWORKWITH,MISCTECHHAVEWORKEDWITH,MISCTECHWANTTOWORKWITH,TOOLSTECHHAVEWORKEDWITH,TOOLSTECHWANTTOWORKWITH,NEWCOLLABTOOLSHAVEWORKEDWITH,NEWCOLLABTOOLSWANTTOWORKWITH,OPSYSPROFESSIONAL USE,OPSYSPERSONAL USE,VERSIONCONTROLSYSTEM,VCINTERACTION,VCHOSTINGPERSONAL USE,VCHOSTINGPROFESSIONAL USE,OFFICESTACKASYNCHAVEWORKEDWITH,OFFICESTACKASYNCWANTTOWORKWITH,OFFICESTACKSYNCHAVEWORKEDWITH,OFFICESTACKSYNCWANTTOWORKWITH,BLOCKCHAIN,NEWSOSITES,SOVISITFREQ,SOACCOUNT,SOPARTFREQ,SOCOMM,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,ACCESSIBILITY,MENTALHEALTH,TBRANCH,ICORPM,WORKEXP,KNOWLEDGE_1,KNOWLEDGE_2,KNOWLEDGE_3,KNOWLEDGE_4,KNOWLEDGE_5,KNOWLEDGE_6,KNOWLEDGE_7,FREQUENCY_1,FREQUENCY_2,FREQUENCY_3,TIMESEARCHING,TIMEANSWERING,ONBOARDING,PROFESSIONALTECH,TRUEFALSE_1,TRUEFALSE_2,TRUEFALSE_3,SURVEYLENGTH,SURVEYEASE,CONVERTEDCOMPYEARLY
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
44536,I am a developer by profession,"Employed, full-time",full in-person,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;edX,4,2,"Developer, full-stack;Educator",2 to 9 employees,I have a great deal of influence,Visit developer communities like Stack Overflo...,Zimbabwe,USD\tUnited States dollar,300.0,Monthly,Bash/Shell;C++;HTML/CSS;Java;JavaScript;Python...,Bash/Shell;Dart;Go;HTML/CSS;Java;JavaScript;Ko...,Cloud Firestore;Microsoft SQL Server;MongoDB;M...,Cloud Firestore;MongoDB;MySQL;PostgreSQL;Fireb...,Firebase;Google Cloud;Heroku,AWS;DigitalOcean;Firebase;Google Cloud;Heroku;...,Django;Express;Node.js;React.js,Django;Express;FastAPI;Next.js;Node.js;React.j...,.NET,NumPy;React Native;Scikit-learn;Spring;TensorFlow,npm,Docker;npm,Android Studio;Atom;Nano;PyCharm;Spyder;Sublim...,Android Studio;Atom;IPython/Jupyter;PyCharm;Sp...,Windows,Empty String,Git,Code editor;Command-line,Empty String,Empty String,ClickUp;Notion,ClickUp;Jira Work Management;Microsoft Planner...,Google Chat;Zoom,Google Chat;Microsoft Teams;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",25-34 years old,Man,No,Straight / Heterosexual,African;Black,None of the above,None of the above,Yes,Independent contributor,2.0,Strongly agree,Disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,60-120 minutes a day,15-30 minutes a day,Very short,Continuous integration (CI) and (more often) c...,No,Yes,Yes,Appropriate in length,Easy,3600.0
31003,I am a developer by profession,"Employed, full-time","hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Udemy;Other,4,3,"Developer, full-stack;Developer, back-end",500 to 999 employees,I have little or no influence,Start a free trial;Visit developer communities...,Zimbabwe,USD\tUnited States dollar,600.0,Monthly,Java,Dart;Java;JavaScript;Python;Scala,MariaDB;MySQL;PostgreSQL;Redis,Cassandra;Elasticsearch;MariaDB;MongoDB;MySQL;...,Empty String,Empty String,Django,Angular;Angular.js;Django;FastAPI;Flask;React.js,Spring,Apache Kafka;Apache Spark;Flutter;Hadoop;Spring,Docker;Kubernetes,Ansible;Docker;Kubernetes;Terraform,IntelliJ;PyCharm;Sublime Text;Webstorm,Android Studio;IntelliJ;PyCharm;Sublime Text;W...,Linux-based,Linux-based,Git,Code editor;Command-line,Empty String,Empty String,Jira Work Management;Microsoft Planner,Confluence;Jira Work Management;Microsoft Plan...,Microsoft Teams,Microsoft Teams;Slack;Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,A few times per week,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,3.0,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Very long,DevOps function,No,Yes,Yes,Too long,Neither easy nor difficult,7200.0
66478,I am a developer by profession,"Independent contractor, freelancer, or self-em...",fully remote,Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;V...,Empty String,8,4,"Developer, front-end;Developer, full-stack;Dev...",100 to 499 employees,I have little or no influence,Start a free trial;Ask developers I know/work ...,Zimbabwe,USD\tUnited States dollar,200.0,Weekly,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;SQL;TypeScript,MongoDB;MySQL,MariaDB;MongoDB;MySQL;PostgreSQL,Firebase;Managed Hosting,DigitalOcean;Firebase;Managed Hosting,Express;jQuery;Node.js;Svelte,Express;jQuery;Laravel;Node.js;Svelte,Empty String,Empty String,Docker;npm,Docker;Kubernetes;npm;Yarn,Visual Studio Code,Sublime Text;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Linux-based;Windows,Git,Command-line,Empty String,Empty String,ClickUp,Microsoft Planner,Slack,Microsoft Teams;Slack,Indifferent,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Disagree,Agree,Neither agree nor disagree,Agree,Disagree,Disagree,Never,1-2 times a week,Never,15-30 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function;Microservices;Developer portal...,No,Yes,Yes,Appropriate in length,Easy,10000.0
71980,I am a developer by profession,"Employed, full-time","hybrid (some remote, some in-person)",Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Udemy;Codecademy;Pluralsight;Other,7,5,"Developer, full-stack;Developer, mobile",100 to 499 employees,I have a great deal of influence,Visit developer communities like Stack Overflo...,Zimbabwe,USD\tUnited States dollar,900.0,Monthly,C#;HTML/CSS;JavaScript;PHP;SQL,C#;Dart;HTML/CSS;JavaScript;PHP;SQL,MySQL,MySQL,Microsoft Azure,Microsoft Azure,jQuery,jQuery;React.js;Vue.js,Empty String,Empty String,Unity 3D,Unity 3D,Android Studio;Notepad++;Visual Studio Code,Android Studio;Notepad++;Visual Studio Code,Windows,Windows,Git,Command-line,Empty String,Empty String,Trello,Trello,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Neither easy nor difficult,10800.0
30291,I am a developer by profession,"Employed, full-time",full in-person,Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Written Tutorials;Stack Overflow;Video-based O...,Empty String,3,5,"Developer, full-stack;Developer, back-end;Deve...",10 to 19 employees,I have a great deal of influence,Visit developer communities like Stack Overflo...,Zimbabwe,USD\tUnited States dollar,1000.0,Monthly,HTML/CSS;Java;JavaScript;PHP;SQL;VBA,HTML/CSS;Java;JavaScript;Kotlin;SQL,MySQL;Firebase Realtime Database;SQLite,MySQL;SQLite,Google Cloud;Managed Hosting;VMware,AWS;Google Cloud,Drupal;Flask;React.js,Empty String,React Native;Spring,Spring,npm,Docker;Kubernetes;Unity 3D;Unreal Engine,Android Studio;IntelliJ;Notepad++;Sublime Text...,Android Studio;IntelliJ;Notepad++;Sublime Text,Windows,Windows,Git,Dedicated version control GUI application,Empty String,Empty String,Trello,Trello,Google Chat;Microsoft Teams;Slack;Zoom,Slack;Zoom,Unsure,Stack Overflow,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,"I have learning differences (e.g., Dyslexic, D...",Yes,Independent contributor,4.0,Agree,Disagree,Agree,Agree,Disagree,Agree,Disagree,1-2 times a week,10+ times a week,1-2 times a week,Over 120 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Observability tools,Yes,No,Yes,Too long,Easy,12000.0

In [92]:
# Aggregation = med,median, vs .. grouping datas based on a common mathematical filter
df["CONVERTEDCOMPYEARLY"].head()

ResponseId
44536     3600.0
31003     7200.0
66478    10000.0
71980    10800.0
30291    12000.0
Name: CONVERTEDCOMPYEARLY, dtype: float64

In [93]:
df["CONVERTEDCOMPYEARLY"].median  # it grabs only numerical values and does the math via those and ignores other values

<bound method NDFrame._add_numeric_operations.<locals>.median of ResponseId
44536     3600.0
31003     7200.0
66478    10000.0
71980    10800.0
30291    12000.0
          ...
51189        0.0
46026        0.0
61618        0.0
69400        0.0
17470        0.0
Name: CONVERTEDCOMPYEARLY, Length: 73268, dtype: float64>

In [94]:
df.median()  #it grabs only numerical values and does the math via those and ignores other values

<ipython-input-94-b93f1d09423d>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()  #it grabs only numerical values and does the math via those and ignores other values

CONVERTEDCOMPYEARLY    5736.0
dtype: float64

In [95]:
df.describe() # Give mathematical description
# -count:Number  of nan value rows
#-mean:mean
#std:Standard deviation

       CONVERTEDCOMPYEARLY
count         7.326800e+04
mean          8.872977e+04
std           5.696963e+05
min           0.000000e+00
25%           0.000000e+00
50%           5.736000e+03
75%           7.027600e+04
max           5.000000e+07

In [96]:
df["SURVEYLENGTH"].value_counts() #Counts and groups by values

Appropriate in length    53883
Too long                 14491
Empty String              2824
Too short                 2070
Name: SURVEYLENGTH, dtype: int64

In [97]:
df["SURVEYLENGTH"].value_counts(normalize=True) #Counts and groups by values as percentages

Appropriate in length    0.735423
Too long                 0.197781
Empty String             0.038543
Too short                0.028252
Name: SURVEYLENGTH, dtype: float64

Group by Function: it involves combination of SPLITING THE OBJECT, APPLYING THE FUNCTION AND COMBINING THE RESULTS

In [98]:
df["COUNTRY"].value_counts()

United States of America                                13543
India                                                    6639
Germany                                                  5395
United Kingdom of Great Britain and Northern Ireland     4190
Canada                                                   2490
                                                        ...
San Marino                                                  1
Solomon Islands                                             1
Saint Kitts and Nevis                                       1
Seychelles                                                  1
Monaco                                                      1
Name: COUNTRY, Length: 181, dtype: int64

In [99]:
#1-SPLITTING THE  OBJECT
country_group = df.groupby(["COUNTRY"])

In [100]:
country_group.get_group("United States of America") #We get all the df where COUNTRY value is USA

,MainBranch,Employment,RemoteWork,CodingActivities,EDLEVEL,LEARNCODE,LEARNCODEONLINE,LEARNCODECOURSESCERT,YEARSCODE,YEARSCODEPRO,DEVTYPE,ORGSIZE,PURCHASEINFLUENCE,BUYNEWTOOL,COUNTRY,CURRENCY,COMPTOTAL,COMPFREQ,LANGUAGEHAVEWORKEDWITH,LANGUAGEWANTTOWORKWITH,DATABASEHAVEWORKEDWITH,DATABASEWANTTOWORKWITH,PLATFORMHAVEWORKEDWITH,PLATFORMWANTTOWORKWITH,WEBFRAMEHAVEWORKEDWITH,WEBFRAMEWANTTOWORKWITH,MISCTECHHAVEWORKEDWITH,MISCTECHWANTTOWORKWITH,TOOLSTECHHAVEWORKEDWITH,TOOLSTECHWANTTOWORKWITH,NEWCOLLABTOOLSHAVEWORKEDWITH,NEWCOLLABTOOLSWANTTOWORKWITH,OPSYSPROFESSIONAL USE,OPSYSPERSONAL USE,VERSIONCONTROLSYSTEM,VCINTERACTION,VCHOSTINGPERSONAL USE,VCHOSTINGPROFESSIONAL USE,OFFICESTACKASYNCHAVEWORKEDWITH,OFFICESTACKASYNCWANTTOWORKWITH,OFFICESTACKSYNCHAVEWORKEDWITH,OFFICESTACKSYNCWANTTOWORKWITH,BLOCKCHAIN,NEWSOSITES,SOVISITFREQ,SOACCOUNT,SOPARTFREQ,SOCOMM,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,ACCESSIBILITY,MENTALHEALTH,TBRANCH,ICORPM,WORKEXP,KNOWLEDGE_1,KNOWLEDGE_2,KNOWLEDGE_3,KNOWLEDGE_4,KNOWLEDGE_5,KNOWLEDGE_6,KNOWLEDGE_7,FREQUENCY_1,FREQUENCY_2,FREQUENCY_3,TIMESEARCHING,TIMEANSWERING,ONBOARDING,PROFESSIONALTECH,TRUEFALSE_1,TRUEFALSE_2,TRUEFALSE_3,SURVEYLENGTH,SURVEYEASE,CONVERTEDCOMPYEARLY
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
64367,"I am not primarily a developer, but I write co...","Employed, full-time",fully remote,Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Video-based Onli...,Coursera;Udemy;Codecademy,2,Less than 1 year,Other (please specify):,500 to 999 employees,I have little or no influence,Start a free trial,United States of America,USD\tUnited States dollar,1.0,Yearly,Empty String,Empty String,Couchbase,Couchbase,AWS;Google Cloud;Heroku,AWS;Google Cloud,Empty String,Empty String,NumPy;Pandas;Scikit-learn,.NET;NumPy;Pandas,Docker;Kubernetes,Docker;Kubernetes;Terraform,Visual Studio Code,Visual Studio Code,Linux-based;macOS,Linux-based;macOS,Git,Code editor;Command-line,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Indifferent,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,45-54 years old,Man,No,Empty String,Empty String,Empty String,Empty String,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Neither easy nor difficult,1.0
37090,I am a developer by profession,"Employed, part-time",fully remote,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Friend or family member,Empty String,Empty String,More than 50 years,49,Academic researcher;Security professional,2 to 9 employees,I have little or no influence,Read ratings or reviews on third party sites l...,United States of America,AUD\tAustralian dollar,12.0,Yearly,TypeScript,Bash/Shell;Fortran,CouchDB;Cloud Firestore;DynamoDB,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,macOS,Empty String,I don't use one,Empty String,Empty String,Empty String,Adobe Workfront,Empty String,Empty String,Empty String,Very favorable,Stack Overflow,Daily or almost daily,No,Empty String,"No, not at all",Prefer not to say,Woman,Prefer not to say,Prefer not to say,I don't know,I am unable to / find it difficult to type,Prefer not to say,Yes,Independent contributor,50.0,Empty String,Empty String,Strongly agree,Empty String,Empty String,Strongly disagree,Empty String,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,Empty String,Very short,None of these,Yes,Empty String,No,Too long,Neither easy nor difficult,8.0
19665,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",fully remote,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Empty String,28,24,"Developer, front-end;Engineer, data;Developer,...",10 to 19 employees,I have a great deal of influence,Other (please specify):,United States of America,USD\tUnited States dollar,3.0,Monthly,Bash/Shell;C;C++;Go;HTML/CSS;JavaScript;Lua;PH...,C;C++;HTML/CSS;JavaScript;LISP;Lua;PHP;TypeScript,MariaDB;MongoDB;PostgreSQL;Redis,MongoDB;Redis,DigitalOcean;OpenStack;OVH,Colocation;DigitalOcean;OpenStack;OVH,jQuery,Empty String,React Native,Hadoop;TensorFlow,Ansible;npm,npm,Atom;CLion;PhpStorm;Vim;Visual Studio Code,Atom;CLion;PhpStorm;Vim;Visual Studio Code,BSD;Linux-based,Linux-based;Windows;Windows Subsystem for Linu...,Git,Code editor;Command-line;Version control hosti...,Empty String,Empty String,Empty String,Empty String,Zoom,Empty String,Favorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",35-44 years old,Man,No,Prefer to self-describe:,"Or, in your own words:","Or, in your own words:;I am blind / have diffi...",None of the above,Yes,People manager,24.0,Agree,Neither agree nor disagree,Agree,Disagree,Strongly agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,Never,Over 120 minutes a day,Over 120 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,36.0
63664,I am a developer by profession,"Employed, full-time",fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Empty String,25,20,"Developer, full-stack",500 to 999 employees,I have little or no influence,Start a free trial;Visit developer communities...,United States of America,UGX\tUgandan shilling,180000.0,Yearly,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,Go;HTML/CSS;JavaScript;SQL;TypeScript,MongoDB;PostgreSQL;Firebase Realtime Database;...,MongoDB;PostgreSQL;Redis,AWS,AWS;Firebase,jQuery;Node.js;React.js,Express;Node.js;React.js,Empty String,Empty String,Homebrew;npm,Homebrew;npm,Visual Studio Code,Visual Studio Code,Linux-based;macOS,macOS,Git,Command-line;Version control hosting service w...,Empty String,Empty String,Empty String,Empty String,Slack;Zoom,Slack,Very unfavorable,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,"No, not at all",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,49.0
27333,I am a developer by profession,"Employed, full-time",fully remote,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Empty String,9,9,Empty String,"10,000 or more employees",I have little or no influence,Empty String,United States of America,USD\tUnited States dollar,90.0,Yearly,Clojure;HTML/CSS;JavaScript;SQL,Clojure;HTML/CSS;JavaScript;SQL,MariaDB;Microsoft SQL Server;MySQL,MariaDB;Microsoft SQL Server;MySQL,AWS;Microsoft Azure,AWS;Microsoft Azure,Express;jQuery;Node.js,Express;jQuery;Node.js,Empty String,Empty String,Empty String,Empty String,IntelliJ;Sublime Text;Visual Studio,Sublime Text,Windows,Linux-based,Git,Command-line,Empty String,Empty String,Empty String,Empty String,Cisco Webex Teams,Empty String,Very unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,Neutral,Empty String,"Or, in your own words:",Yes,Prefer to self-describe:,"Or, in your own words:","Or, in your own words:","Or, in your own words:",No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Difficult,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40212,"I am not primarily a developer, but I write co...","Employed, part-time",fully remote,Hobby;School or academic work,Primary/elementary school,Online Courses or Certification;Colleague,Empty String,Empty String,7,Less than 1 year,"Developer, full-stack;Designer",20 to 99 employees,I have little or no influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,Empty String,Empty String,C++;HTML/CSS;JavaScript;PowerShell;Python;SQL,Assembly;Java;PHP,MySQL;SQLite,Empty String,AWS;Heroku,Empty String,Flask;jQuery;React.js,Empty String,NumPy;Pandas;Scikit-learn;TensorFlow;Torch/PyT...,Empty String,Yarn,Unity 3D,Notepad++;Visual Studio;Visual Studio Code,Empty String,Windows,Windows,Git,Dedicated version control GUI application,Empty String,Empty String,Notion,Empty String,Zoom,Empty String,Unfavorable,Stack Overflow,Multiple times per day,No,Empty String,"No, not really",Under 18 years old,Man,No,Straight / Heterosexual,White;Hispanic or Latino/a,None of the above,None of the above,Yes,Independent contributor,1.0,Disagree,Disagree,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,Developer portal or other central places to fi...,No,Yes,Yes,Appropriate in length,Neither easy nor difficult,0.0
40211,I am learning to code,"Student, full-time",Empty String,Empty String,Primary/elementary school,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Stack Overflow;H...,Empty String,5,Empty String,Empty String,Empty String,Empty String,Ask developers I know/work with,United States of America,Empty String,Empty String,Empty String,C#;HTML/CSS;Python,C#;Go;HTML/CSS;Java;Python;Rust,Empty String,Empty String,Empty String,Empty String,Flask,Flask;Node.js;React.js;Vue.js,Empty String,Empty String,Unity 3D,Docker;Unity 3D,Visual Studio Code,Visual Studio Code,Windows,Windows,Git,Version control hosting service web GUI,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",Under 18 years old,Man,No,Straight / Heterosexual,Southeast Asian,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,0.0
58630,I am learning to code,"Student, full-time;Independent contractor, fre...",Empty String,Hobby;Freelance/contract work,"Secondary school (e.g. American high school, G...",Friend or family member;Other online resources...,Technical documentation;Blogs;Programming Game...,Other,6,Empty String,Empty String,Empty String,Empty String,Start a free trial;Ask developers I know/work ...,United States of America,Empty String,Empty String,Empty String,Bash/Shell;C++;HTML/CSS;Java;JavaScript;PHP;Po...,C++;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,MariaDB;MongoDB;MySQL;PostgreSQL,PostgreSQL,Heroku,Heroku,Express;Node.js;React.js,Express;Next.js;Node.js;React.js,Empty String,Empty String,npm,npm,IntelliJ;Notepad++;Visual Studio Code,Android Studio;IntelliJ;Visual Studio Code,Empty String,Windows,Git,Code editor;Command-line,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,Neutral,Empty String,Empty String,Empty String,Empty String,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Neither easy nor difficult,0.0
12087,"I am not primarily a developer, but I write co...","Employed, full-time;Student, full-time","hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training,Empty String,Empty String,5,Empty String,Student;Educator;Academic researcher;Scientist,Empty String,Empty String,Visit developer communities like Stack Overflo...,United States of America,Empty String,Empty String,Empty String,Julia;Python;R;SAS;SQL,Julia,PostgreSQL;SQLite,Empty String,AWS;Google Cloud,Empty String,Empty String,Empty String,Pandas,Empty String,Empty String,Empty String,Visual Studio Code,Visual Studio Code,Linux-based,Windows,Git,Dedicated version control GUI application,Empty String,Empty String,Empty String,Empty String,Google Chat;Slack;Zoom,Google Chat;Slack;Zoom,Very unfavorable,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,0.0
13135,I am a developer by profession,"Student, part-time;Employed, part-time","hybrid (some remote, some in-person)",Hobby;School or academic work,"Associate degree (A.A., A.S., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Empty String,10,Empty String,"Developer, desktop or enterprise applications;...",Empty String,Empty String,Start a free trial;Visit developer communities...,United States of America,Empty String,Empty String,Empty String,Bash/Shell;C++;Groovy;Java;LISP;SQL;VBA,Bash/Shell;C++;Groovy;Java;LISP;SQL,Microsoft SQL Server;MySQL,Microsoft SQL Server,Empty String,Empty String,Empty String,Empty String,.NET,.NET,Empty String,Empty String,Notepad++;Vim;Visual Studio;Visual Studio Code,Notepad++;Vim;Visual Studio;Visual Studio Code,Windows,Linux-based,Git,Code editor;Command-line,Empty String,Empty String,Trello,Empty String,Cisco Webex Teams;Zoom,Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",18-24 years old,Empty String,Empty String,Empty String,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Easy,0.0

In [101]:
filt=(df["COUNTRY"]=="United States of America")  #It's the same as groupby method
df.loc[filt]

,MainBranch,Employment,RemoteWork,CodingActivities,EDLEVEL,LEARNCODE,LEARNCODEONLINE,LEARNCODECOURSESCERT,YEARSCODE,YEARSCODEPRO,DEVTYPE,ORGSIZE,PURCHASEINFLUENCE,BUYNEWTOOL,COUNTRY,CURRENCY,COMPTOTAL,COMPFREQ,LANGUAGEHAVEWORKEDWITH,LANGUAGEWANTTOWORKWITH,DATABASEHAVEWORKEDWITH,DATABASEWANTTOWORKWITH,PLATFORMHAVEWORKEDWITH,PLATFORMWANTTOWORKWITH,WEBFRAMEHAVEWORKEDWITH,WEBFRAMEWANTTOWORKWITH,MISCTECHHAVEWORKEDWITH,MISCTECHWANTTOWORKWITH,TOOLSTECHHAVEWORKEDWITH,TOOLSTECHWANTTOWORKWITH,NEWCOLLABTOOLSHAVEWORKEDWITH,NEWCOLLABTOOLSWANTTOWORKWITH,OPSYSPROFESSIONAL USE,OPSYSPERSONAL USE,VERSIONCONTROLSYSTEM,VCINTERACTION,VCHOSTINGPERSONAL USE,VCHOSTINGPROFESSIONAL USE,OFFICESTACKASYNCHAVEWORKEDWITH,OFFICESTACKASYNCWANTTOWORKWITH,OFFICESTACKSYNCHAVEWORKEDWITH,OFFICESTACKSYNCWANTTOWORKWITH,BLOCKCHAIN,NEWSOSITES,SOVISITFREQ,SOACCOUNT,SOPARTFREQ,SOCOMM,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,ACCESSIBILITY,MENTALHEALTH,TBRANCH,ICORPM,WORKEXP,KNOWLEDGE_1,KNOWLEDGE_2,KNOWLEDGE_3,KNOWLEDGE_4,KNOWLEDGE_5,KNOWLEDGE_6,KNOWLEDGE_7,FREQUENCY_1,FREQUENCY_2,FREQUENCY_3,TIMESEARCHING,TIMEANSWERING,ONBOARDING,PROFESSIONALTECH,TRUEFALSE_1,TRUEFALSE_2,TRUEFALSE_3,SURVEYLENGTH,SURVEYEASE,CONVERTEDCOMPYEARLY
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
64367,"I am not primarily a developer, but I write co...","Employed, full-time",fully remote,Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Video-based Onli...,Coursera;Udemy;Codecademy,2,Less than 1 year,Other (please specify):,500 to 999 employees,I have little or no influence,Start a free trial,United States of America,USD\tUnited States dollar,1.0,Yearly,Empty String,Empty String,Couchbase,Couchbase,AWS;Google Cloud;Heroku,AWS;Google Cloud,Empty String,Empty String,NumPy;Pandas;Scikit-learn,.NET;NumPy;Pandas,Docker;Kubernetes,Docker;Kubernetes;Terraform,Visual Studio Code,Visual Studio Code,Linux-based;macOS,Linux-based;macOS,Git,Code editor;Command-line,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Indifferent,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,45-54 years old,Man,No,Empty String,Empty String,Empty String,Empty String,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Neither easy nor difficult,1.0
37090,I am a developer by profession,"Employed, part-time",fully remote,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Friend or family member,Empty String,Empty String,More than 50 years,49,Academic researcher;Security professional,2 to 9 employees,I have little or no influence,Read ratings or reviews on third party sites l...,United States of America,AUD\tAustralian dollar,12.0,Yearly,TypeScript,Bash/Shell;Fortran,CouchDB;Cloud Firestore;DynamoDB,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,macOS,Empty String,I don't use one,Empty String,Empty String,Empty String,Adobe Workfront,Empty String,Empty String,Empty String,Very favorable,Stack Overflow,Daily or almost daily,No,Empty String,"No, not at all",Prefer not to say,Woman,Prefer not to say,Prefer not to say,I don't know,I am unable to / find it difficult to type,Prefer not to say,Yes,Independent contributor,50.0,Empty String,Empty String,Strongly agree,Empty String,Empty String,Strongly disagree,Empty String,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,Empty String,Very short,None of these,Yes,Empty String,No,Too long,Neither easy nor difficult,8.0
19665,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",fully remote,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Empty String,28,24,"Developer, front-end;Engineer, data;Developer,...",10 to 19 employees,I have a great deal of influence,Other (please specify):,United States of America,USD\tUnited States dollar,3.0,Monthly,Bash/Shell;C;C++;Go;HTML/CSS;JavaScript;Lua;PH...,C;C++;HTML/CSS;JavaScript;LISP;Lua;PHP;TypeScript,MariaDB;MongoDB;PostgreSQL;Redis,MongoDB;Redis,DigitalOcean;OpenStack;OVH,Colocation;DigitalOcean;OpenStack;OVH,jQuery,Empty String,React Native,Hadoop;TensorFlow,Ansible;npm,npm,Atom;CLion;PhpStorm;Vim;Visual Studio Code,Atom;CLion;PhpStorm;Vim;Visual Studio Code,BSD;Linux-based,Linux-based;Windows;Windows Subsystem for Linu...,Git,Code editor;Command-line;Version control hosti...,Empty String,Empty String,Empty String,Empty String,Zoom,Empty String,Favorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",35-44 years old,Man,No,Prefer to self-describe:,"Or, in your own words:","Or, in your own words:;I am blind / have diffi...",None of the above,Yes,People manager,24.0,Agree,Neither agree nor disagree,Agree,Disagree,Strongly agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,Never,Over 120 minutes a day,Over 120 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,36.0
63664,I am a developer by profession,"Employed, full-time",fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Empty String,25,20,"Developer, full-stack",500 to 999 employees,I have little or no influence,Start a free trial;Visit developer communities...,United States of America,UGX\tUgandan shilling,180000.0,Yearly,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,Go;HTML/CSS;JavaScript;SQL;TypeScript,MongoDB;PostgreSQL;Firebase Realtime Database;...,MongoDB;PostgreSQL;Redis,AWS,AWS;Firebase,jQuery;Node.js;React.js,Express;Node.js;React.js,Empty String,Empty String,Homebrew;npm,Homebrew;npm,Visual Studio Code,Visual Studio Code,Linux-based;macOS,macOS,Git,Command-line;Version control hosting service w...,Empty String,Empty String,Empty String,Empty String,Slack;Zoom,Slack,Very unfavorable,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,"No, not at all",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,49.0
27333,I am a developer by profession,"Employed, full-time",fully remote,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Empty String,9,9,Empty String,"10,000 or more employees",I have little or no influence,Empty String,United States of America,USD\tUnited States dollar,90.0,Yearly,Clojure;HTML/CSS;JavaScript;SQL,Clojure;HTML/CSS;JavaScript;SQL,MariaDB;Microsoft SQL Server;MySQL,MariaDB;Microsoft SQL Server;MySQL,AWS;Microsoft Azure,AWS;Microsoft Azure,Express;jQuery;Node.js,Express;jQuery;Node.js,Empty String,Empty String,Empty String,Empty String,IntelliJ;Sublime Text;Visual Studio,Sublime Text,Windows,Linux-based,Git,Command-line,Empty String,Empty String,Empty String,Empty String,Cisco Webex Teams,Empty String,Very unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,Neutral,Empty String,"Or, in your own words:",Yes,Prefer to self-describe:,"Or, in your own words:","Or, in your own words:","Or, in your own words:",No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Difficult,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40212,"I am not primarily a developer, but I write co...","Employed, part-time",fully remote,Hobby;School or academic work,Primary/elementary school,Online Courses or Certification;Colleague,Empty String,Empty String,7,Less than 1 year,"Developer, full-stack;Designer",20 to 99 employees,I have little or no influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,Empty String,Empty String,C++;HTML/CSS;JavaScript;PowerShell;Python;SQL,Assembly;Java;PHP,MySQL;SQLite,Empty String,AWS;Heroku,Empty String,Flask;jQuery;React.js,Empty String,NumPy;Pandas;Scikit-learn;TensorFlow;Torch/PyT...,Empty String,Yarn,Unity 3D,Notepad++;Visual Studio;Visual Studio Code,Empty String,Windows,Windows,Git,Dedicated version control GUI application,Empty String,Empty String,Notion,Empty String,Zoom,Empty String,Unfavorable,Stack Overflow,Multiple times per day,No,Empty String,"No, not really",Under 18 years old,Man,No,Straight / Heterosexual,White;Hispanic or Latino/a,None of the above,None of the above,Yes,Independent contributor,1.0,Disagree,Disagree,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,Developer portal or other central places to fi...,No,Yes,Yes,Appropriate in length,Neither easy nor difficult,0.0
40211,I am learning to code,"Student, full-time",Empty String,Empty String,Primary/elementary school,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Stack Overflow;H...,Empty String,5,Empty String,Empty String,Empty String,Empty String,Ask developers I know/work with,United States of America,Empty String,Empty String,Empty String,C#;HTML/CSS;Python,C#;Go;HTML/CSS;Java;Python;Rust,Empty String,Empty String,Empty String,Empty String,Flask,Flask;Node.js;React.js;Vue.js,Empty String,Empty String,Unity 3D,Docker;Unity 3D,Visual Studio Code,Visual Studio Code,Windows,Windows,Git,Version control hosting service web GUI,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",Under 18 years old,Man,No,Straight / Heterosexual,Southeast Asian,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,0.0
58630,I am learning to code,"Student, full-time;Independent contractor, fre...",Empty String,Hobby;Freelance/contract work,"Secondary school (e.g. American high school, G...",Friend or family member;Other online resources...,Technical documentation;Blogs;Programming Game...,Other,6,Empty String,Empty String,Empty String,Empty String,Start a free trial;Ask developers I know/work ...,United States of America,Empty String,Empty String,Empty String,Bash/Shell;C++;HTML/CSS;Java;JavaScript;PHP;Po...,C++;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,MariaDB;MongoDB;MySQL;PostgreSQL,PostgreSQL,Heroku,Heroku,Express;Node.js;React.js,Express;Next.js;Node.js;React.js,Empty String,Empty String,npm,npm,IntelliJ;Notepad++;Visual Studio Code,Android Studio;IntelliJ;Visual Studio Code,Empty String,Windows,Git,Code editor;Command-line,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,Neutral,Empty String,Empty String,Empty String,Empty String,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Too long,Neither easy nor difficult,0.0
12087,"I am not primarily a developer, but I write co...","Employed, full-time;Student, full-time","hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training,Empty String,Empty String,5,Empty String,Student;Educator;Academic researcher;Scientist,Empty String,Empty String,Visit developer communities like Stack Overflo...,United States of America,Empty String,Empty String,Empty String,Julia;Python;R;SAS;SQL,Julia,PostgreSQL;SQLite,Empty String,AWS;Google Cloud,Empty String,Empty String,Empty String,Pandas,Empty String,Empty String,Empty String,Visual Studio Code,Visual Studio Code,Linux-based,Windows,Git,Dedicated version control GUI application,Empty String,Empty String,Empty String,Empty String,Google Chat;Slack;Zoom,Google Chat;Slack;Zoom,Very unfavorable,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Neither easy nor difficult,0.0
13135,I am a developer by profession,"Student, part-time;Employed, part-time","hybrid (some remote, some in-person)",Hobby;School or academic work,"Associate degree (A.A., A.S., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Empty String,10,Empty String,"Developer, desktop or enterprise applications;...",Empty String,Empty String,Start a free trial;Visit developer communities...,United States of America,Empty String,Empty String,Empty String,Bash/Shell;C++;Groovy;Java;LISP;SQL;VBA,Bash/Shell;C++;Groovy;Java;LISP;SQL,Microsoft SQL Server;MySQL,Microsoft SQL Server,Empty String,Empty String,Empty String,Empty String,.NET,.NET,Empty String,Empty String,Notepad++;Vim;Visual Studio;Visual Studio Code,Notepad++;Vim;Visual Studio;Visual Studio Code,Windows,Linux-based,Git,Code editor;Command-line,Empty String,Empty String,Trello,Empty String,Cisco Webex Teams;Zoom,Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",18-24 years old,Empty String,Empty String,Empty String,Empty String,None of the above,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Empty String,Appropriate in length,Easy,0.0

In [102]:
#2-APPLY FUNCTION
filt=(df["COUNTRY"]=="India")  #It's the same as groupby method
df.loc[filt]["EDLEVEL"].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          4121
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       1129
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     704
Some college/university study without earning a degree                                 334
Primary/elementary school                                                              158
Something else                                                                          80
Professional degree (JD, MD, etc.)                                                      46
Empty String                                                                            23
Other doctoral degree (Ph.D., Ed.D., etc.)                                              23
Associate degree (A.A., A.S., etc.)                                                     21
Name: EDLEVEL, dtype: int64

In [103]:
country_group["ORGSIZE"].value_counts().head(10)

COUNTRY      ORGSIZE
Afghanistan  Empty String                                          35
             2 to 9 employees                                       6
             100 to 499 employees                                   5
             10 to 19 employees                                     4
             500 to 999 employees                                   4
             Just me - I am a freelancer, sole proprietor, etc.     4
             I don’t know                                           3
             1,000 to 4,999 employees                               2
             10,000 or more employees                               2
             20 to 99 employees                                     2
Name: ORGSIZE, dtype: int64

In [104]:
country_group["ORGSIZE"].value_counts().loc["China"] #We can filter it by using loc and passing the index

ORGSIZE
Empty String                                          311
10,000 or more employees                               64
20 to 99 employees                                     61
100 to 499 employees                                   51
1,000 to 4,999 employees                               45
2 to 9 employees                                       27
10 to 19 employees                                     21
5,000 to 9,999 employees                               17
500 to 999 employees                                   14
Just me - I am a freelancer, sole proprietor, etc.     13
I don’t know                                            8
Name: ORGSIZE, dtype: int64

In [108]:
country_group["CONVERTEDCOMPYEARLY"].median().loc["Germany"]

38388.0

In [114]:
country_group["CONVERTEDCOMPYEARLY"].agg(["mean","median"])

mean      136051.116867
median     62463.500000
Name: Canada, dtype: float64

In [115]:
country_group["CONVERTEDCOMPYEARLY"].agg(["mean","median"]).loc["Canada"]

mean      136051.116867
median     62463.500000
Name: Canada, dtype: float64

In [122]:
filt=(df["COUNTRY"]=="India")  #It's the same as groupby method
df.loc[filt]["LEARNCODECOURSESCERT"].str.contains("Udemy")

ResponseId
39916     True
65743     True
58971     True
4239      True
36976     True
         ...
42378     True
20954    False
16552    False
16570    False
52819     True
Name: LEARNCODECOURSESCERT, Length: 6639, dtype: bool

In [127]:
df.loc[filt]["CodingActivities"].str.contains("Hobby").sum()

3128

In [129]:
osize_group =df.groupby("ORGSIZE")
osize_group["CodingActivities"].apply(lambda x: x.str.contains("Hobby").sum()) 
# We grouped dataframe by the values of the column called "ORGSIZE" and checked how much the 
# "Hobby" value each group has using apply method,which allows user to apply methods to series

ORGSIZE
1,000 to 4,999 employees                              4166
10 to 19 employees                                    3029
10,000 or more employees                              5139
100 to 499 employees                                  6761
2 to 9 employees                                      3352
20 to 99 employees                                    7524
5,000 to 9,999 employees                              1650
500 to 999 employees                                  2596
Empty String                                          6363
I don’t know                                           684
Just me - I am a freelancer, sole proprietor, etc.    1658
Name: CodingActivities, dtype: int64

In [135]:
c_group = df.groupby("COUNTRY")
c_group["LANGUAGEHAVEWORKEDWITH"].apply(lambda x:x.str.contains("Python").sum())

**CEANING DATA & CASTING DATATYPES**

In [136]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}
df = pd.DataFrame(people)

In [137]:
df.dropna() #Deletes all the rows contains NaN

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [138]:
df.dropna(axis="index",how="any") # deletes any indexes with NaN   axis="columns": drops columns

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [140]:
df.dropna(axis="columns",how="any") # deletes columns contain NaN

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [141]:
df.dropna(axis="index",how="any",subset=["email"]) #in subset,it only looks for given columns,in that case "email" column for default NaN values.We'll treat custom non values different

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
5   None      NaN      Anonymous@email.com  None

In [142]:
df.dropna(axis="index",how="all",subset=["last","email"]) #drop all the default NaN values that dont have "last" and "email".

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
5   None      NaN      Anonymous@email.com  None

In [147]:
df.replace("NA",np.nan,inplace=True) #changing Custom na values to default na

In [150]:
df.replace("None",np.nan,inplace=True) #changing Custom na values to default na
df

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None      NaN      Anonymous@email.com  None
6    NaN      NaN                      NaN   NaN

In [152]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [153]:
df.fillna("Missing") #filling na values

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  Missing       36
4  Missing  Missing                  Missing  Missing
5  Missing  Missing      Anonymous@email.com  Missing
6  Missing  Missing                  Missing  Missing

In [155]:
df.dtypes #shows columns' type

first    object
last     object
email    object
age      object
dtype: object

In [157]:
df["age"].astype(int) # it won't covert because na values can't be converted.So there will be an error

TypeError: ignored

In [166]:
df["age"]=df["age"].fillna(0).astype(float) #Changing the type

In [167]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [176]:
filt=(df["age"] == 0)  # Assigning mean value to 0s
df.loc[filt,"age"] = df["age"].mean()

In [177]:
df

   first     last                    email        age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33.000000
1   Jane      Doe        JaneDoe@email.com  55.000000
2   John      Doe        JohnDoe@email.com  63.000000
3  Chris  Schafer                     None  36.000000
4    NaN      NaN                      NaN  26.714286
5   None      NaN      Anonymous@email.com  26.714286
6    NaN      NaN                      NaN  26.714286

In [180]:
df = pd.read_csv("/content/drive/MyDrive/pandas/survey_results_public.csv",na_values=["NA","Missing"]) # Turning custom na values to default ones with read_csv

In [182]:
type(df)

pandas.core.frame.DataFrame

In [183]:
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [189]:
df["YearsCode"].unique()

array([nan, '14', '20', '8', '15', '3', '1', '6', '37', '5', '12', '22',
       '11', '4', '7', '13', '36', '2', '25', '10', '40', '16', '27',
       '24', '19', '9', '17', '18', '26', 'More than 50 years', '29',
       '30', '32', 'Less than 1 year', '48', '45', '38', '39', '28', '23',
       '43', '21', '41', '35', '50', '33', '31', '34', '46', '44', '42',
       '47', '49'], dtype=object)

In [190]:
df["YearsCode"].replace('More than 50 years',0,inplace=True)
df["YearsCode"].replace('Less than 1 year',0,inplace=True)
df["YearsCode"]

0        NaN
1        NaN
2         14
3         20
4          8
        ...
73263      8
73264      6
73265     42
73266     50
73267     16
Name: YearsCode, Length: 73268, dtype: object

In [194]:
df["YearsCode"].unique()

array([nan, '14', '20', '8', '15', '3', '1', '6', '37', '5', '12', '22',
       '11', '4', '7', '13', '36', '2', '25', '10', '40', '16', '27',
       '24', '19', '9', '17', '18', '26', 0, '29', '30', '32', '48', '45',
       '38', '39', '28', '23', '43', '21', '41', '35', '50', '33', '31',
       '34', '46', '44', '42', '47', '49'], dtype=object)

In [195]:
df["YearsCode"] = df["YearsCode"].astype(float)

In [199]:
mean_age=df["YearsCode"].mean()

In [200]:
df["YearsCode"].replace(0,mean_age,inplace=True)

In [201]:
df["YearsCode"].unique()

array([       nan, 14.       , 20.       ,  8.       , 15.       ,
        3.       ,  1.       ,  6.       , 37.       ,  5.       ,
       12.       , 22.       , 11.       ,  4.       ,  7.       ,
       13.       , 36.       ,  2.       , 25.       , 10.       ,
       40.       , 16.       , 27.       , 24.       , 19.       ,
        9.       , 17.       , 18.       , 26.       , 12.1283313,
       29.       , 30.       , 32.       , 48.       , 45.       ,
       38.       , 39.       , 28.       , 23.       , 43.       ,
       21.       , 41.       , 35.       , 50.       , 33.       ,
       31.       , 34.       , 46.       , 44.       , 42.       ,
       47.       , 49.       ])

**DATETIME & TIME SERIES**

In [202]:
df=pd.read_csv("/content/drive/MyDrive/pandas/ETH_1h.csv")
df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [204]:
df.loc[0, "Date"].day_name() #Since "Date" column consist from str values, we can't use a datetime method on it

AttributeError: ignored

In [206]:
df["Date"] = pd.to_datetime(df["Date"],format="%Y-%m-%d %I-%p") #We turned into "DayTime" type

In [207]:
df["Date"]

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [209]:
df.loc[0,"Date"].day_name()

'Friday'

In [212]:
# We can change strings to daytrime whilst specifying dataframe

d_parser= lambda x:pd.datetime.strptime(x,"%Y-%m-%d %I-%p")
df = pd.read_csv("/content/drive/MyDrive/pandas/ETH_1h.csv",parse_dates=["Date"],date_parser=d_parser)
df

<ipython-input-212-cdbff1a4431e>:3: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  d_parser= lambda x:pd.datetime.strptime(x,"%Y-%m-%d %I-%p")

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
23669 2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670 2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671 2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672 2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673 2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [213]:
df["Date"].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: object

In [215]:
df["DayOfWeek"] = df["Date"].dt.day_name() #Accesing date_time class using "dt"
df

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [216]:
df["Date"].min()

Timestamp('2017-07-01 11:00:00')

In [217]:
df["Date"].max()

Timestamp('2020-03-13 20:00:00')

In [218]:
df["Date"].max() - df["Date"].min() # Range of Days

Timedelta('986 days 09:00:00')

In [219]:
filt = (df["Date"] >= "2020") #pandas will know this string is for datetime
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
1744,2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
1745,2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
1746,2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
1747,2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
1748,2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [222]:
filt = (df["Date"] >= "2019" ) & (df["Date"] < "2020" ) 
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
1749,2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
1750,2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
1751,2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
1752,2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
1753,2019-12-31 19:00:00,ETHUSD,128.69,128.69,127.60,127.84,1169847.84,Tuesday
...,...,...,...,...,...,...,...,...
10504,2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
10505,2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
10506,2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
10507,2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
10508,2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [224]:
filt = (df["Date"] >= pd.to_datetime("2019-01-01") ) & (df["Date"] < pd.to_datetime("2020-01-01") ) 
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
1749,2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
1750,2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
1751,2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
1752,2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
1753,2019-12-31 19:00:00,ETHUSD,128.69,128.69,127.60,127.84,1169847.84,Tuesday
...,...,...,...,...,...,...,...,...
10504,2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
10505,2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
10506,2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
10507,2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
10508,2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [225]:
df.set_index("Date",inplace=True)

In [226]:
df

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...
2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [227]:
df["2019"]

<ipython-input-227-01f1be04b9d5>:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  df["2019"]

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
2019-12-31 19:00:00,ETHUSD,128.69,128.69,127.60,127.84,1169847.84,Tuesday
...,...,...,...,...,...,...,...
2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [228]:
df["2020-01":"2020-02"]

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2020-02-29 23:00:00,ETHUSD,223.35,223.58,216.83,217.31,1927939.88,Saturday
2020-02-29 22:00:00,ETHUSD,223.48,223.59,222.14,223.35,535998.57,Saturday
2020-02-29 21:00:00,ETHUSD,224.63,225.14,222.74,223.48,561158.03,Saturday
2020-02-29 20:00:00,ETHUSD,225.31,225.33,223.50,224.63,511648.65,Saturday
2020-02-29 19:00:00,ETHUSD,225.09,225.85,223.87,225.31,1250856.20,Saturday
...,...,...,...,...,...,...,...
2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [229]:
df["2020-01":"2020-02"]["Close"].mean()

195.1655902777778

In [230]:
df["2020-01":"2020-02"].head(24)

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2020-02-29 23:00:00,ETHUSD,223.35,223.58,216.83,217.31,1927939.88,Saturday
2020-02-29 22:00:00,ETHUSD,223.48,223.59,222.14,223.35,535998.57,Saturday
2020-02-29 21:00:00,ETHUSD,224.63,225.14,222.74,223.48,561158.03,Saturday
2020-02-29 20:00:00,ETHUSD,225.31,225.33,223.50,224.63,511648.65,Saturday
2020-02-29 19:00:00,ETHUSD,225.09,225.85,223.87,225.31,1250856.20,Saturday
2020-02-29 18:00:00,ETHUSD,225.53,226.17,224.50,225.09,496543.91,Saturday
2020-02-29 17:00:00,ETHUSD,222.68,225.53,222.24,225.53,611136.47,Saturday
2020-02-29 16:00:00,ETHUSD,224.17,225.93,222.36,222.68,694384.75,Saturday
2020-02-29 15:00:00,ETHUSD,223.35,225.88,221.80,224.17,550893.74,Saturday
2020-02-29 14:00:00,ETHUSD,224.42,224.42,221.15,223.35,1479928.44,Saturday
2020-02-29 13:00:00,ETHUSD,225.29,225.37,222.87,224.42,1076646.41,Saturday
2020-02-29 12:00:00,ETHUSD,226.50,226.50,224.14,225.29,359022.09,Saturday
2020-02-29 11:00:00,ETHUSD,223.11,226.74,222.19,226.50,684186.89,Saturday
2020-02-29 10:00:00,ETHUSD,225.86,228.11,222.77,223.11,1053817.02,Saturday
2020-02-29 09:00:00,ETHUSD,228.78,228.78,225.10,225.86,880482.27,Saturday
2020-02-29 08:00:00,ETHUSD,229.73,230.38,228.32,228.78,222951.78,Saturday
2020-02-29 07:00:00,ETHUSD,228.67,230.06,227.84,229.73,603444.28,Saturday
2020-02-29 06:00:00,ETHUSD,232.13,233.00,228.03,228.67,1573935.25,Saturday
2020-02-29 05:00:00,ETHUSD,232.09,233.32,231.16,232.13,855793.43,Saturday
2020-02-29 04:00:00,ETHUSD,230.41,233.00,230.32,232.09,754164.18,Saturday
2020-02-29 03:00:00,ETHUSD,229.23,230.83,228.17,230.41,1173484.59,Saturday
2020-02-29 02:00:00,ETHUSD,227.45,230.33,227.19,229.23,1120127.13,Saturday
2020-02-29 01:00:00,ETHUSD,229.81,231.00,227.38,227.45,696316.26,Saturday
2020-02-29 00:00:00,ETHUSD,227.37,232.20,227.04,229.81,1435038.82,Saturday

In [232]:
df["2020-01-01"]["High"].max()

<ipython-input-232-5f9726cdfd06>:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  df["2020-01-01"]["High"].max()

132.68

Resampling

In [235]:
highs=df["High"].resample("D").max() # it gives each values of "High" on daily basis because of resampling by "D"
 #"D","W"...Check resampling types from the documentation

In [236]:
highs["2020-01-01"]

132.68

In [237]:
df.resample("W").mean() #Resample all dataframe

<ipython-input-237-5f54b50f91fd>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.resample("W").mean() #Resample all dataframe

                  Open        High         Low       Close        Volume
Date
2017-07-02  268.066486  271.124595  264.819730  268.202162  2.185035e+06
2017-07-09  261.337024  262.872917  259.186190  261.062083  1.337349e+06
2017-07-16  196.193214  199.204405  192.722321  195.698393  2.986756e+06
2017-07-23  212.351429  215.779286  209.126310  212.783750  4.298593e+06
2017-07-30  203.496190  205.110357  201.714048  203.309524  1.581729e+06
...                ...         ...         ...         ...           ...
2020-02-16  255.021667  257.255238  252.679762  255.198452  2.329087e+06
2020-02-23  265.220833  267.263690  262.948512  265.321905  1.826094e+06
2020-03-01  236.720536  238.697500  234.208750  236.373988  2.198762e+06
2020-03-08  229.923571  231.284583  228.373810  229.817619  1.628910e+06
2020-03-15  176.937521  179.979487  172.936239  176.332821  4.259828e+06

[142 rows x 5 columns]

In [238]:
df.resample("W").agg({"Close":"mean","High":"max","Low":"min","Volume":"sum"})

                 Close    High     Low        Volume
Date
2017-07-02  268.202162  293.73  253.23  8.084631e+07
2017-07-09  261.062083  285.00  231.25  2.246746e+08
2017-07-16  195.698393  240.33  130.26  5.017750e+08
2017-07-23  212.783750  249.40  153.25  7.221637e+08
2017-07-30  203.309524  229.99  178.03  2.657305e+08
...                ...     ...     ...           ...
2020-02-16  255.198452  290.00  216.31  3.912867e+08
2020-02-23  265.321905  287.13  242.36  3.067838e+08
2020-03-01  236.373988  278.13  209.26  3.693920e+08
2020-03-08  229.817619  253.01  196.00  2.736569e+08
2020-03-15  176.332821  208.65   90.00  4.983998e+08

[142 rows x 4 columns]

**READ & WRITE DATA**

In [241]:
new_df=df.resample("W").agg({"Close":"mean","High":"max","Low":"min","Volume":"sum"})

In [242]:
new_df.to_csv("/content/drive/MyDrive/pandas/new_df.csv") #Write .csv